(function(){var p,r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ba=aa(this),t=function(a,b){if(b)a:{var c=ba;a=a.split(".");for(var d=0;d< 
a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&r(c,a,{configurable:!0,writable:!0,value:b})}},ea=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},u=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ea(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},fa=function(a){if(!(a instanceof Array)){a=u(a); 
for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a};t("globalThis",function(a){return a||ba},"es_2020","es3");t("Symbol",function(a){if(a)return a;var b=function(l,h){this.X=l;r(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.X};a=Math.random()*1E9>>>0;var c="jscomp_symbol_"+a+"_",d=0,e=function(l){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(l||"")+"_"+d++,l)};return e},"es6","es3"); 
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");r(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(ea(this))}});return a},"es6","es3");var ha=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}; 
t("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),g=Object.seal({}),n=new a([[k,2],[g,3]]);if(n.get(k)!=2||n.get(g)!=3)return!1;n.delete(k);n.set(g,4);return!n.has(k)&&n.get(g)==4}catch(q){return!1}}function c(){}function d(k){var g=typeof k;return g==="object"&&k!==null||g==="function"}function e(k){if(!v(k,h)){var g=new c;r(k,h,{value:g})}}function l(k){var g=Object[k];g&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return g(n)})} 
if(b())return a;var h="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var m=0,f=function(k){this.u=(m+=Math.random()+1).toString();if(k){k=u(k);for(var g;!(g=k.next()).done;)g=g.value,this.set(g[0],g[1])}};f.prototype.set=function(k,g){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!v(k,h))throw Error("WeakMap key fail: "+k);k[h][this.u]=g;return this};f.prototype.get=function(k){return d(k)&&v(k,h)?k[h][this.u]:void 0};f.prototype.has=function(k){return d(k)&&v(k, 
h)&&v(k[h],this.u)};f.prototype.delete=function(k){return d(k)&&v(k,h)&&v(k[h],this.u)?delete k[h][this.u]:!1};return f},"es6","es3"); 
t("Map",function(a){function b(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var f=Object.seal({x:4}),k=new a(u([[f,"s"]]));if(k.get(f)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var g=k.entries(),n=g.next();if(n.done||n.value[0]!=f||n.value[1]!="s")return!1;n=g.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!g.next().done?!1:!0}catch(q){return!1}}if(b())return a;var c=new WeakMap,d=function(f){this[0]={};this[1]= 
h();this.size=0;if(f){f=u(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}};d.prototype.set=function(f,k){f=f===0?0:f;var g=e(this,f);g.list||(g.list=this[0][g.id]=[]);g.entry?g.entry.value=k:(g.entry={next:this[1],l:this[1].l,head:this[1],key:f,value:k},g.list.push(g.entry),this[1].l.next=g.entry,this[1].l=g.entry,this.size++);return this};d.prototype.delete=function(f){f=e(this,f);return f.entry&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.entry.l.next= 
f.entry.next,f.entry.next.l=f.entry.l,f.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].l=h();this.size=0};d.prototype.has=function(f){return!!e(this,f).entry};d.prototype.get=function(f){return(f=e(this,f).entry)&&f.value};d.prototype.entries=function(){return l(this,function(f){return[f.key,f.value]})};d.prototype.keys=function(){return l(this,function(f){return f.key})};d.prototype.values=function(){return l(this,function(f){return f.value})};d.prototype.forEach= 
function(f,k){for(var g=this.entries(),n;!(n=g.next()).done;)n=n.value,f.call(k,n[1],n[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(f,k){var g;var n=(g=k)&&typeof g;n=="object"||n=="function"?c.has(g)?g=c.get(g):(n=""+ ++m,c.set(g,n),g=n):g="p_"+g;if((n=f[0][g])&&v(f[0],g))for(f=0;f<n.length;f++){var q=n[f];if(k!==k&&q.key!==q.key||k===q.key)return{id:g,list:n,index:f,entry:q}}return{id:g,list:n,index:-1,entry:void 0}},l=function(f,k){var g=f[1];return ha(function(){if(g){for(;g.head!= 
f[1];)g=g.l;for(;g.next!=g.head;)return g=g.next,{done:!1,value:k(g)};g=null}return{done:!0,value:void 0}})},h=function(){var f={};return f.l=f.next=f.head=f},m=0;return d},"es6","es3"); 
t("Set",function(a){function b(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var d=Object.seal({x:4}),e=new a(u([d]));if(!e.has(d)||e.size!=1||e.add(d)!=e||e.size!=1||e.add({x:4})!=e||e.size!=2)return!1;var l=e.entries(),h=l.next();if(h.done||h.value[0]!=d||h.value[1]!=d)return!1;h=l.next();return h.done||h.value[0]==d||h.value[0].x!=4||h.value[1]!=h.value[0]?!1:l.next().done}catch(m){return!1}}if(b())return a;var c=function(d){this.i=new Map;if(d){d= 
u(d);for(var e;!(e=d.next()).done;)e=e.value,this.add(e)}this.size=this.i.size};c.prototype.add=function(d){d=d===0?0:d;this.i.set(d,d);this.size=this.i.size;return this};c.prototype.delete=function(d){d=this.i.delete(d);this.size=this.i.size;return d};c.prototype.clear=function(){this.i.clear();this.size=0};c.prototype.has=function(d){return this.i.has(d)};c.prototype.entries=function(){return this.i.entries()};c.prototype.values=function(){return this.i.values()};c.prototype.keys=c.prototype.values; 
c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(d,e){var l=this;this.i.forEach(function(h){return d.call(e,h,h,l)})};return c},"es6","es3");t("Object.values",function(a){return a?a:a=function(b){var c=[],d;for(d in b)v(b,d)&&c.push(b[d]);return c}},"es8","es3");t("Object.entries",function(a){return a?a:a=function(b){var c=[],d;for(d in b)v(b,d)&&c.push([d,b[d]]);return c}},"es8","es3"); 
t("Number.isFinite",function(a){return a?a:a=function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}},"es6","es3");t("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6","es3");t("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991},"es6","es3");t("Number.isInteger",function(a){return a?a:a=function(b){return Number.isFinite(b)?b===Math.floor(b):!1}},"es6","es3"); 
t("Number.isSafeInteger",function(a){return a?a:a=function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}},"es6","es3");var ia=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var l=c++;return{value:b(l,a[l]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};t("Array.prototype.entries",function(a){return a?a:a=function(){return ia(this,function(b,c){return[b,c]})}},"es6","es3"); 
t("Array.prototype.values",function(a){return a?a:a=function(){return ia(this,function(b,c){return c})}},"es8","es3");/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var w=this||self,y=function(a,b,c,d){a=a.split(".");d=d||w;for(var e;a.length&&(e=a.shift());)if(a.length||b===void 0)d=d[e]&&d[e]!==Object.prototype[e]?d[e]:d[e]={};else if(!c&&ja(b)&&ja(d[e]))for(var l in b)b.hasOwnProperty(l)&&(d[e][l]=b[l]);else d[e]=b},ja=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"};var ka,A;a:{for(var la=["CLOSURE_FLAGS"],B=w,ma=0;ma<la.length;ma++)if(B=B[la[ma]],B==null){A=null;break a}A=B}var na=A&&A[610401301],oa=ka=na!=null?na:!1;var pa=!1;function qa(){var a=w.navigator;return a&&(a=a.userAgent)?a:""}var C=null,ra,sa=w.navigator;ra=sa?sa.userAgentData||null:null;function D(a){var b=C==null?qa():C;return b.indexOf(a)!=-1};var ta=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ua=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a==="string"?a.split(""):a,l=0;l<d;l++)l in e&&b.call(c,e[l],l,a)};var va;var ya=void 0;if((ya=ya===void 0?!1:ya)||oa||pa){var za=ra;va=!!za&&za.brands.length>0}else va=!1;var Aa=va?!1:D("Trident")||D("MSIE"),Ba;if(Ba=D("Gecko")){var Ca,Da=C==null?qa():C;Ca=Da.toLowerCase().indexOf("webkit")!=-1;Ba=!(Ca&&!D("Edge"))}var Ea=Ba&&!(D("Trident")||D("MSIE"))&&!D("Edge");function F(a){a.pa=!0;return a}F(function(a){return a!==null&&a!==void 0},"exists");var Fa=F(function(a){return typeof a==="number"},"number");Ga(0);F(function(a){return Number.isSafeInteger(a)},"isSafeInteger");F(function(a){return Number.isInteger(a)},"isInteger");F(function(a){return Number.isFinite(a)},"isFinite");var Ha=F(function(a){return typeof a==="string"},"string");Ga("");F(function(a){return a.trim()!==""},"isNotBlank");F(function(a){return a.trim()===""},"isBlank");F(function(a){return typeof a==="boolean"},"boolean"); 
var Ia=F(function(a){return typeof a==="bigint"},"bigint");F(function(a){return a===null},"null");F(function(a){return a===void 0},"undefined");F(function(a){return a==null},"null | undefined");function Ga(a){return F(function(b){return b===a},function(){throw Error("basicPrettyPrint should only be used in DEBUG mode");})}F(function(a){return a!=null&&typeof a==="object"&&typeof a.then==="function"},"Thenable");var Ja=F(function(a){return typeof a==="function"},"Function"); 
F(function(a){return Ja(a)?a.pa===!0:!1},"isGuard");Ka(Date);F(function(a){return!isNaN(a)},"isValidDate");F(function(a){return a.global},"isGlobalRegExp");F(function(a){return a.sticky},"isStickyRegExp");F(function(a){return!!a&&(typeof a==="object"||typeof a==="function")},"object"); 
function Ka(a){return F(function(b){return b instanceof a},function(){var b=a.displayName;b&&typeof b==="string"||(b=a.name,b&&typeof b==="string"||(b=String(a),b=(b=/function\s+([^\(]+)/m.exec(b))?b[1]:"(Anonymous)"));return b})}F(function(){return!0},"unknown");La();La();function La(){return F(function(a){return Array.isArray(a)},"Array<unknown>")}Ma();Ma();function Ma(){return F(function(a){return a instanceof Set},"Set<unknown>")}Na();Na(); 
function Na(){return F(function(a){return a instanceof Map},"Map<unknown, unknown>")};var G=typeof w.BigInt==="function"&&typeof w.BigInt(0)==="bigint";F(function(a){return G?Ia(a):Ha(a)&&/^(?:-?[1-9]\d*|0)$/.test(a)},"gbigint");F(function(a){return G?a>=Oa&&a<=Pa:a[0]==="-"?H(a,Qa):H(a,Ra)},"isSafeInt52");var Qa=Number.MIN_SAFE_INTEGER.toString(),Oa=G?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ra=Number.MAX_SAFE_INTEGER.toString(),Pa=G?BigInt(Number.MAX_SAFE_INTEGER):void 0;F(function(a){return G?a>=Sa&&a<=Ta:a[0]==="-"?H(a,"-9223372036854775808"):H(a,"9223372036854775807")},"isValidSignedInt64"); 
var Sa=G?BigInt("-9223372036854775808"):void 0,Ta=G?BigInt("9223372036854775807"):void 0;F(function(a){return G?a>=Ua&&a<=Va:a[0]==="-"?!1:H(a,"18446744073709551615")},"isValidUnsignedInt64");var Ua=G?BigInt(0):void 0,Va=G?BigInt("18446744073709551615"):void 0;function H(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Wa=!1;if(Wa&&typeof Proxy!=="undefined"){var I=Xa;new Proxy({},{getPrototypeOf:I,setPrototypeOf:I,isExtensible:I,preventExtensions:I,getOwnPropertyDescriptor:I,defineProperty:I,has:I,get:I,set:I,deleteProperty:I,apply:I,construct:I})}function Xa(){throw Error();};function Ya(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};var Za=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};/* 
 
 Copyright Google LLC 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function J(a){return{valueOf:a}.valueOf()};var K={};var fb="goog#html",gb=globalThis.trustedTypes,hb=gb,ib;function jb(){var a=null;if(fb===""||!hb)return a;try{var b=function(c){return c};a=hb.createPolicy(fb,{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};var kb=function(a,b){this.va=b};kb.prototype.toString=function(){return this.va};new kb(K,"about:blank");new kb(K,"about:invalid#zClosurez");var lb=J(function(){return typeof URL==="function"}),mb=["data:","http:","https:","mailto:","ftp:"];var P=function(a,b){this.O=b};P.prototype.toString=function(){return this.O+""};function Q(a){var b;ib===void 0&&(ib=jb());a=(b=ib)?b.createHTML(a):a;return a=new P(K,a)}function nb(a){if(a instanceof P)return a.O;a="";throw Error(a);};function ob(a,b){if(a.nodeType===1){var c="",d=a.tagName;if(/^(script|style)$/i.test(d))throw Error(c);}a.innerHTML=nb(b)};function pb(a){try{return new URL(a,window.document.baseURI)}catch(b){return new URL("about:invalid")}};function qb(a,b){var c=b.createRange();c.selectNode(b.body);a=Q(a);return c.createContextualFragment(nb(a))};function rb(a){a=a.nodeName;return typeof a==="string"?a:"FORM"}function sb(a){a=a.nodeType;return a===1||typeof a!=="number"};var R=function(a,b,c,d,e){this.ca=a;this.J=b;this.da=c;this.ma=d;this.K=e};R.prototype.oa=function(a){return a!=="FORM"&&(this.ca.has(a)||this.J.has(a))};R.prototype.ia=function(a,b){b=this.J.get(b);var c;return((c=b)==null?0:c.has(a))?b.get(a):this.da.has(a)?{h:1}:(c=this.ma.get(a))?c:this.K&&[].concat(fa(this.K)).some(function(d){return a.indexOf(d)===0})?{h:1}:{h:0}};var tb="ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" "), 
ub=[["A",new Map([["href",{h:7}]])],["AREA",new Map([["href",{h:7}]])],["LINK",new Map([["href",{h:5,conditions:new Map([["rel",new Set("alternate author bookmark canonical cite help icon license next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" "))]])}]])],["SOURCE",new Map([["src",{h:5}],["srcset",{h:6}]])],["IMG",new Map([["src",{h:5}],["srcset",{h:6}]])],["VIDEO",new Map([["src",{h:5}]])],["AUDIO",new Map([["src",{h:5}]])]],vb="title aria-atomic aria-autocomplete aria-busy aria-checked aria-current aria-disabled aria-dropeffect aria-expanded aria-haspopup aria-hidden aria-invalid aria-label aria-level aria-live aria-multiline aria-multiselectable aria-orientation aria-posinset aria-pressed aria-readonly aria-relevant aria-required aria-selected aria-setsize aria-sort aria-valuemax aria-valuemin aria-valuenow aria-valuetext alt align autocapitalize autocomplete autocorrect autofocus autoplay bgcolor border cellpadding cellspacing checked cite color cols colspan controls controlslist coords crossorigin datetime disabled download draggable enctype face formenctype frameborder height hreflang hidden inert ismap label lang loop max maxlength media minlength min multiple muted nonce open playsinline placeholder preload rel required reversed role rows rowspan selected shape size sizes slot span spellcheck start step summary translate type usemap valign value width wrap itemscope itemtype itemid itemprop itemref".split(" "), 
wb=[["dir",{h:3,conditions:J(function(){return new Map([["dir",new Set(["auto","ltr","rtl"])]])})}],["async",{h:3,conditions:J(function(){return new Map([["async",new Set(["async"])]])})}],["loading",{h:3,conditions:J(function(){return new Map([["loading",new Set(["eager","lazy"])]])})}],["poster",{h:5}],["target",{h:3,conditions:J(function(){return new Map([["target",new Set(["_self","_blank"])]])})}]],xb=new R(new Set(tb),new Map(ub),new Set(vb),new Map(wb),void 0),yb=new R(new Set(tb.concat(["BUTTON", 
"INPUT"])),new Map(ub),new Set(J(function(){return vb.concat(["class","id","name"])})),new Map(J(function(){return wb.concat([["style",{h:1}]])})),void 0),zb=new R(new Set(J(function(){return tb.concat("STYLE TITLE INPUT TEXTAREA BUTTON LABEL".split(" "))})),new Map(ub),new Set(J(function(){return vb.concat(["class","id","tabindex","contenteditable","name"])})),new Map(J(function(){return wb.concat([["style",{h:1}]])})),new Set(["data-","aria-"]));var Ab=function(a,b,c,d,e,l){this.R=a;this.U=c;this.T=d;this.B=e;this.M=l};p=Ab.prototype;p.H=function(a){return a=this.xa(a)};p.xa=function(a){var b=document.implementation.createHTMLDocument("");a=this.Aa(a,b);b=b.body;b.appendChild(a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"));return b=Q(b)}; 
p.Aa=function(a,b){var c=this;a=qb(a,b);a=document.createTreeWalker(a,5,function(m){return c.ta(m)});for(var d=a.nextNode(),e=b.createDocumentFragment(),l=e;d!==null;){var h=void 0;if(d.nodeType===3)this.U&&l.nodeName==="STYLE"?(d=this.U(d.data),h=this.createTextNode(d)):h=this.za(d);else if(sb(d))h=this.ya(d,b);else throw b="",Error(b);l.appendChild(h);if(d=a.firstChild())l=h;else for(;!(d=a.nextSibling())&&(d=a.parentNode());)l=l.parentNode}return e};p.createTextNode=function(a){return document.createTextNode(a)}; 
p.za=function(a){return this.createTextNode(a.data)}; 
p.ya=function(a,b){var c=rb(a);b=b.createElement(c);a=a.attributes;var d=u(a),e=d.next(),l;try{for(;!e.done;e=d.next()){var h=e.value,m=h,f=m.name,k=m.value,g=this.R.ia(f,c);if(this.Ba(g.conditions,a))switch(g.h){case 1:S(b,f,k);break;case 2:throw Error();case 3:S(b,f,k.toLowerCase());break;case 4:if(this.T){var n=this.T(k);S(b,f,n)}else S(b,f,k);break;case 5:if(this.B){m={type:2,attributeName:f,I:c};var q=pb(k),L=this.B(q,m);L&&S(b,f,L.toString())}else S(b,f,k);break;case 6:if(this.B){m={type:2, 
attributeName:f,I:c};var wa,x=void 0,E=void 0,z=[],ca=u(k.split(",")),M=ca.next();try{for(;!M.done;M=ca.next()){x=M.value;var $a=u(x.trim().split(/\s+/,2)),Yb=$a.next().value,Zb=$a.next().value,$b=Yb,ac=Zb;z.push({url:$b,D:ac})}}finally{M&&!M.done&&(E=ca.return)&&E.call(ca)}x=wa={A:z};E={A:[]};var da=u(x.A),N=da.next(),ab;try{for(;!N.done;N=da.next()){var bb=N.value,bc=pb(bb.url),cb=this.B(bc,m);cb&&E.A.push({url:cb.toString(),D:bb.D})}}finally{N&&!N.done&&(ab=da.return)&&ab.call(da)}S(b,f,Bb(E))}else S(b, 
f,k);break;case 7:m=k;if(this.M){x={type:2,attributeName:f,I:c};var dc=pb(k),db=this.M(dc,x);if(db===null)break;m=db.toString()}x=m;a:if(E=void 0,z=x,lb){try{E=new URL(z)}catch(ec){var O="https:";break a}O=E.protocol}else b:{var eb=document.createElement("a");try{eb.href=z}catch(ec){O=void 0;break b}var xa=eb.protocol;O=xa===":"||xa===""?"https:":xa}m=O!==void 0&&mb.indexOf(O.toLowerCase())!==-1?x:"about:invalid#zClosurez";S(b,f,m)}}}finally{e&&!e.done&&(l=d.return)&&l.call(d)}return b}; 
p.ta=function(a){if(a.nodeType===3)return 1;if(!sb(a))return 2;a=rb(a);return a===null?2:this.R.oa(a)?1:2};p.Ba=function(a,b){if(!a)return!0;a=u(a);var c=a.next(),d;try{for(;!c.done;c=a.next()){var e=c.value,l=u(e),h=l.next().value,m=l.next().value,f=h,k=m,g=void 0,n=(g=b.getNamedItem(f))==null?void 0:g.value;if(n&&!k.has(n))return!1}}finally{c&&!c.done&&(d=a.return)&&d.call(a)}return!0};function S(a,b,c){a.setAttribute(b,c)} 
function Bb(a){return a.A.map(function(b){var c=b;b=c.url;c=c.D;return""+b+(c?" "+c:"")}).join(" , ")}var Cb=J(function(){return new Ab(xb,K)}),Db=J(function(){return new Ab(yb,K)}),Eb=J(function(){return new Ab(zb,K)});var Fb={0:1,1:1},Gb={0:.1,1:.1};function Hb(a,b){try{Eb.H(a)}catch(c){return T(b,"H_SLSANITIZE"),!0}try{Db.H(a)}catch(c){return T(b,"H_RSANITIZE"),!0}try{Cb.H(a)}catch(c){return T(b,"H_SANITIZE"),!0}return!1}function T(a,b,c){var d=Ib?Ib:typeof window!=="undefined"&&window.navigator&&window.navigator.sendBeacon!==void 0?navigator.sendBeacon.bind(navigator):Jb;b={host:window.location.hostname,type:b,additionalData:c};d("https://csp.withgoogle.com/csp/lcreport/"+a.P,JSON.stringify(b))} 
function Jb(a,b){var c=new XMLHttpRequest;c.open("POST",a);c.setRequestHeader("Content-Type","application/json");c.send(b)}var Ib;var Kb=function(a,b){b=b===void 0?document:b;return b.createElement(String(a).toLowerCase())};var Lb=function(a,b){return typeof b==="string"?a.getElementById(b):b};var Mb=Za(function(){var a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});w.addEventListener("test",null,b)}catch(c){}return a});function Nb(a){return a?a.passive&&Mb()?a:a.capture||!1:!1}function Ob(a,b,c,d){return typeof a.addEventListener==="function"?(a.addEventListener(b,c,Nb(d)),!0):!1}function Pb(a,b,c,d){return typeof a.removeEventListener==="function"?(a.removeEventListener(b,c,Nb(d)),!0):!1};function Qb(a,b,c,d,e){c=c===void 0?null:c;d=d===void 0?!1:d;e=e===void 0?!1:e;return Rb(a,b,c,!1,d,e)} 
function Rb(a,b,c,d,e,l){l=l===void 0?!1:l;a.google_image_requests||(a.google_image_requests=[]);var h=Kb("IMG",a.document);if(c||e){var m=function(f){c&&c(f);if(e){f=a.google_image_requests;var k=ta(f,h);k>=0&&Array.prototype.splice.call(f,k,1)}Pb(h,"load",m);Pb(h,"error",m)};Ob(h,"load",m);Ob(h,"error",m)}d&&(h.referrerPolicy="no-referrer");l&&(h.attributionSrc="");h.src=b;a.google_image_requests.push(h);return h} 
function Sb(a,b,c){c=c===void 0?!1:c;var d;if(d=a.navigator)d=a.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&typeof a.navigator.sendBeacon==="function"?a.navigator.sendBeacon(b):Qb(a,b,void 0,c)};var Tb=document,U=window;var Ub=null;function Vb(a){a=a===void 0?w:a;return(a=a.performance)&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function Wb(a){a=a===void 0?w:a;return(a=a.performance)&&a.now?a.now():null};var Xb=function(a,b,c,d,e,l){d=d===void 0?0:d;this.label=a;this.type=b;this.value=c;this.duration=d;this.slotId=e;this.taskId=l;this.uniqueId=Math.random()};var V=w.performance,cc=!!(V&&V.mark&&V.measure&&V.clearMarks),W=Za(function(){var a;if(a=cc){var b;a=void 0;a=a===void 0?window:a;if(Ub===null){Ub="";try{var c="";try{c=a.top.location.hash}catch(d){c=a.location.hash}c&&(Ub=(b=c.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(d){}}b=Ub;a=!!b.indexOf&&b.indexOf("1337")>=0}return a}),X=function(a,b){this.events=[];this.na=b||w;var c=null;b&&(b.google_js_reporting_queue=b.google_js_reporting_queue||[],this.events=b.google_js_reporting_queue,c=b.google_measure_js_timing); 
this.o=W()||(c!=null?c:Math.random()<a)};X.prototype.disable=function(){this.o=!1;this.events!==this.na.google_js_reporting_queue&&(W()&&ua(this.events,fc),this.events.length=0)};X.prototype.wa=function(a){!this.o||this.events.length>2048||this.events.push(a)};var fc=function(a){a&&V&&W()&&(V.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),V.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}; 
X.prototype.start=function(a,b){if(!this.o)return null;var c=Wb()||Vb();a=new Xb(a,b,c);b="goog_"+a.label+"_"+a.uniqueId+"_start";V&&W()&&V.mark(b);return a};X.prototype.end=function(a){if(this.o&&Fa(a.value)){var b=Wb()||Vb();a.duration=b-a.value;b="goog_"+a.label+"_"+a.uniqueId+"_end";V&&W()&&V.mark(b);this.wa(a)}};var Y=function(a,b){a=a===void 0?4E3:a;b=b===void 0?"&":b;this.qa=a;this.G=b;this.C={};this.sa=0;this.v=[]},ic=function(a,b,c,d,e){var l=[];Ya(a,function(h,m){(h=hc(h,b,c,d,e))&&l.push(m+"="+h)});return l.join(b)},hc=function(a,b,c,d,e){if(a==null)return"";b=b||"&";c=c||",$";Ha(c)&&(c=c.split(""));if(a instanceof Array){if(d||(d=0),d<c.length){for(var l=[],h=0;h<a.length;h++)l.push(hc(a[h],b,c,d+1,e));return l.join(c[d])}}else if(typeof a==="object")return e||(e=0),e<2?encodeURIComponent(ic(a,b,c, 
d,e+1)):"...";return encodeURIComponent(String(a))};Y.prototype.aa=function(a,b){this.v.push(a);this.C[a]=b};Y.prototype.Z=function(a,b){var c=this.sa++,d={};d[a]=b;a=[d];this.aa(c,a)}; 
Y.prototype.la=function(a,b,c){a=a+"//"+b+c;var d=this.ja()-c.length;if(d<0)return"";this.v.sort(function(k,g){return k-g});c=null;b="";for(var e=0;e<this.v.length;e++)for(var l=this.v[e],h=this.C[l],m=0;m<h.length;m++){if(!d){c=c==null?l:c;break}var f=ic(h[m],this.G,",$");if(f){f=b+f;if(d>=f.length){d-=f.length;a+=f;b=this.G;break}c=c==null?l:c}}d="";c!=null&&(d=""+b+"trn="+c);return a+d}; 
Y.prototype.ja=function(){var a=1,b;for(b in this.C)b.length>a&&(a=b.length);return this.qa-3-a-this.G.length-1};var jc=function(){};var kc=function(a,b,c,d){d=d===void 0?!1:d;this.domain=a;this.path=b;this.ga=c;this.ba=d;this.protocol="https:";this.S=Math.random()};kc.prototype.Ca=function(a){a>=0&&a<=1&&(this.S=a)};kc.prototype.ra=function(a,b,c,d,e){c=c===void 0?!1:c;if(this.Da(c,d))try{if(b instanceof Y)var l=b;else l=new Y,Ya(b,function(m,f){l.Z(f,m)});var h=l.la(this.protocol,this.domain,this.path+a+"&");h&&(typeof e!=="undefined"?Qb(w,h,e):this.ba?Sb(w,h):Qb(w,h))}catch(m){}}; 
kc.prototype.Da=function(a,b){b=b||this.ga;a=a?this.S:Math.random();return a<b};var lc,mc=new X(1,window);function nc(a){var b=window;a!=null&&(b.google_measure_js_timing=a);b.google_measure_js_timing||mc.disable()}function oc(a){var b;lc=(b=a)!=null?b:new kc("pagead2.googlesyndication.com","/pagead/gen_204?id=",.01);typeof window.google_srt!=="number"&&(window.google_srt=Math.random());lc.Ca(window.google_srt);window.document.readyState==="complete"?nc():mc.o&&Ob(window,"load",function(){nc()})}oc();function Z(a,b){a=a===null?"null":a===void 0?"undefined":a;var c;if(c=b){var d,e;c=Math.random()<((e=(d=b.Ha)!=null?d:Fb[b.P[0]])!=null?e:0)}if(c&&window.SAFEVALUES_REPORTING!==!1&&"DocumentFragment"in window){var l,h;Math.random()<((h=(l=b.Ga)!=null?l:Gb[b.P[0]])!=null?h:0)&&T(b,"HEARTBEAT");d=Hb(a,b);d||(d=a,d instanceof P?e=d:(e=String(d).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;"),e=Q(e)),e.toString()!==d&&T(b,"H_ESCAPE"))}return Q(a)} 
;var pc=function(a,b){b=b===void 0?null:b;this.j=null;this.N=!1;this.m=null;this.V=b||"gam";this.W=a+"_"+this.V};p=pc.prototype;p.ka=function(){var a=(new Date).valueOf();this.m==null&&(U.gdbg_offset?this.m=U.gdbg_offset:(this.m=a,U.gdbg_offset=this.m));return a-this.m};p.ha=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}; 
p.fa=function(){if(this.j==null&&!this.N)if(this.j=U.open("","GoogleDebug_"+this.W,"width=1100, height=600, status=no,resizable=yes, scrollbars=yes")){var a="Google Ad Manager Debug Output";this.V!="gam"&&(a="Google Debug Output");var b=this.j.document,c="";c+="<html>";c+="<head><title>"+a+"</title><style>";c+="h2 {font-size: 1em;margin: 0 0 0.5em 0;color: #353C43}";c+="th {background: #e5e5e5;font-weight: normal;color: #444444;";c+="text-align: left;}";c+="td {border-bottom: 1px solid #dddddd}"; 
c+="tbody tr:hover {background: #ffffcc}";c+=".dn {display: none;} .lightText {color: #a0a0a0;}";c+="\x3c/style>";c+="</head>";c+="<body><h2>"+a+"</h2><br/>";c+='Page URL: <span id="pageUrl"></span><br/><br/>';c+='<form action="" method="post">';c+='<table id="google_slot_table" width="100%" class="dn" ';c+='cellspacing="0">';c+="<thead><tr><th>&nbsp;";c+='<span id="numSlots">0</span> slots on page</th>';c+="<th>&nbsp;</th>";c+="<th>&nbsp;</th>";c+="</tr><tr>";c+="<th>&nbsp;&nbsp;Ad Slot Name</th>"; 
c+="<th>Ad Request URL</th>";c+="<th>Delivery Analysis ";c+='<span class="lightText">(login required)</span></th>';c+="</tr></thead>";c+="<tbody>";c+='<tr class="dn"><td></td>';c+="<td></td></tr>";c+="</tbody></table><br/>";c+='<table id="google_msg_table" width="100%" cellspacing="0">';c+="<thead><tr><th>Offset (msec)</th><th>Type</th>";c+="<th>Message</th></tr></thead>";c+='<tbody id="google_msg_body">';c+='<tr class="dn"><td></td><td></td><td></td></tr>';c+="</tbody></table></form></body></html>"; 
a=b;c=Z(c);a.write(nb(c));b.getElementById("pageUrl").textContent=Tb.URL;b.close();b.getElementById("google_slot_table")}else this.N=!0};p.F=function(a,b){return'<font color="'+qc[a]+'">'+b+"</font>"}; 
p.Fa=function(a,b,c){var d=this.j;if(d)if(d=this.j.document.getElementById("google_msg_table"),d!=null){d=d.insertRow(-1);var e=d.insertCell(0);ob(e,Z(this.F(a,""+this.ka())));e=d.insertCell(1);ob(e,Z(this.F(a,a+"&nbsp;&nbsp;")));d=d.insertCell(2);c||(b=this.ha(b));ob(d,Z(this.F(a,b)))}else alert("fails to add to console: "+a+", "+b)};p.Y=function(){if(this.j==null){var a="gdbg_console_"+this.W;U[a]?this.j=U[a]:(this.fa(),U[a]=this.j)}};p.Ea=function(a){this.Fa("Error",a,!1)}; 
var qc={Information:"black",Warning:"orange",Error:"red",Internal:"green"};var rc=null;function sc(a){if(!rc){var b=void 0,c=(b=b===void 0?null:b)||"gam";b="gdbg_logger_showcompanionads_"+c;if(!U[b]){U[b]=new pc("showcompanionads",c);a:{if(c=Tb.URL){var d=RegExp(".*[&#?]google_debug(=[^&]*)?(&.*)?$");try{var e=d.exec(decodeURIComponent(c));if(e){var l=e[1]&&e[1].length>1?e[1].substring(1):"true";break a}}catch(h){}}l=""}l.length>0&&U[b].Y()}rc=U[b]}rc.Ea(a)} 
var tc=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=b.length,d=0;d<c;++d){var e=b[d],l=e.getAttribute("target");l&&(a.push({ea:e,ua:l}),e.removeAttribute("target"))}return a},uc=function(a){if(a)for(var b=a.length,c=0;c<b;++c){var d=a[c];d.ea.setAttribute("target",d.ua)}};function vc(){return!0}function wc(){var a=[],b=xc();if(b&&(b=b.getSlots())){b=u(b);var c=b.next(),d;try{for(;!c.done;c=b.next()){var e=c.value,l,h={};if(e){h.slotId=e.getSlotId().getId();h.adType=e.get("ad_type");var m=void 0,f=e.getSizes(),k=[];if(f&&Array.isArray(f))for(var g=0,n=f.length;g<n;g++)m={},typeof f[g]!=="string"&&(m.adWidth=f[g].getWidth(),m.adHeight=f[g].getHeight(),k.push(m));var q=k;h.adSizes=q}h=l=h;a.push(h)}}finally{c&&!c.done&&(d=b.return)&&d.call(b)}}return a} 
function yc(a,b,c){b={method:"gscac",caller:c};var d=jc;c=d;var e="L";c.L&&c.hasOwnProperty(e)||(d=new d,c.L=d);c=[];!b.eid&&c.length&&(b.eid=c.toString());lc.ra("gpt_sca",b,!0,.001,void 0);if((b=xc())&&a&&Array.isArray(a)&&(c=b.getSlotIdMap()))for(d=0,e=a.length;d<e;d++){var l=a[d],h=l.slotId;if(h in c){h=c[h];var m=(m=xc())&&m.isSlotAPersistentRoadblock!=null?m.isSlotAPersistentRoadblock(h):!1;if(!m&&l.adContent){m=h.getSlotId().getDomId();if(m=Lb(document,m))m.style.display="";if(l.friendlyIframeRendering){var f= 
h;m=l.adContent;var k=l.adWidth,g=l.adHeight,n=f.getSlotId().getDomId(),q=Lb(document,n);if(q){if(n=Lb(document,n))n.textContent="";n="google_companion_"+f.getSlotId().getId();k=k?k:f.getSizes()[0].getWidth();f=g?g:f.getSizes()[0].getHeight();g=document;g=g.createElement("iframe");g.id=n;g.name=n;k!=null&&f!=null&&(g.width=String(k),g.height=String(f));g.vspace="0";g.hspace="0";g.allowTransparency="true";g.scrolling="no";g.marginWidth="0";g.marginHeight="0";g.frameBorder="0";g.style.border="0";g.style.verticalAlign= 
"bottom";g.src="about:blank";q.appendChild(g);f=g;if(Aa){try{var L=!!f.contentWindow.document}catch(z){L=!1}if(L){g=tc();try{window.frames[f.name].contents=m,f.src='javascript:window["contents"]'}catch(z){sc("Could not write third party content into IE iframe: "+z.message)}finally{uc(g)}}else{g=tc();q="google-ad-content-"+(Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36));try{window[q]=m;var wa='document.domain = "'+document.domain+ 
'";var adContent = window.parent["'+(q+'"];window.parent["')+(q+'"] = null;document.write(adContent);document.close();');f.src='javascript:\'<script type="text/javascript">'+wa+"\x3c/script>'"}catch(z){window[q]=null,sc("Could not write third party content into IE iframe with modified document.domain: "+z.message)}finally{uc(g)}}}else try{var x=f.contentWindow?f.contentWindow.document:f.contentDocument;Ea&&x.open("text/html","replace");f=x;var E=Z(m);f.write(nb(E));x.close()}catch(z){sc("Could not write content into iframe using the DOM standards method. "+ 
z.message)}}b.slotRenderEnded(h,l.adWidth,l.adHeight)}l.onAdContentSet!=null&&(m=l.onAdContentSet,h=h.getSlotId().getDomId(),h=Lb(document,h),m.call(l,h))}}}}function xc(){if(typeof googletag!="undefined"&&googletag&&typeof googletag.companionAds=="function"){var a=googletag.companionAds();return a}return null}function zc(a){a&&(a+="&label=elementview&value=0",Qb(U,a))}y("googleCompanionsServicePresent",vc,!0,void 0);y("googleGetCompanionAdSlots",wc,!0,void 0); 
y("googleSetCompanionAdContents",yc,!0,void 0);y("google_companion_error",zc,!0,void 0);var Ac=xc();if(Ac&&Ac.onImplementationLoaded)Ac.onImplementationLoaded();}).call(this);
