var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return $jscomp.createTemplateTagFirstArgWithRaw(a,a)};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};$jscomp.ASSUME_ES2020=!1;$jscomp.ASSUME_ES6=$jscomp.ASSUME_ES2020;$jscomp.ASSUME_ES5=$jscomp.ASSUME_ES6;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.INSTRUMENT_ASYNC_CONTEXT=!0;$jscomp.defineProperty=$jscomp.ASSUME_ES5||typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.ASSUME_ES2020?globalThis:$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE=typeof Symbol==="function"&&typeof Symbol("x")==="symbol";$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;
$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var JSCompiler_inline_result$jscomp$0,classes$jscomp$inline_1="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");$jscomp.global.BigInt64Array&&(classes$jscomp$inline_1.push("BigInt64"),classes$jscomp$inline_1.push("BigUint64"));JSCompiler_inline_result$jscomp$0=classes$jscomp$inline_1;$jscomp.TYPED_ARRAY_CLASSES=JSCompiler_inline_result$jscomp$0;
$jscomp.polyfillTypedArrayMethod=function(a,b,c,d){if(b)for(var f=0;f<$jscomp.TYPED_ARRAY_CLASSES.length;f++){var g=$jscomp.TYPED_ARRAY_CLASSES[f]+"Array.prototype."+a;$jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(g,b,c,d):$jscomp.polyfillUnisolated(g,b,c,d)}};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b){var c=$jscomp.global;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))return;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c){var d=a.split("."),f=d.length===1;a=d[0];a=!f&&a in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<d.length-1;g++){var m=d[g];if(!(m in a))return;a=a[m]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&c==="es6"?a[d]:null;b=b(c);b!=null&&(f?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]===void 0&&(f=Math.random()*1E9>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+f+"$"+d),f=$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(a,f,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Object.is",function(a){return a?a:a=function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:a=function(b,c){var d=this;d instanceof String&&(d=String(d));var f=d.length;c=c||0;for(c<0&&(c=Math.max(c+f,0));c<f;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:a=function(b,c){var d=$jscomp.checkStringArgs(this,b,"includes");return d.indexOf(b,c||0)!==-1}},"es6","es3");
var cloud_discoveryengine={collect:function(a,b,c,d,f){function g(e){return typeof e==="string"&&e.length>0}function m(e){var k=!0,h=(0,$jscomp.makeIterator)(["apiKey","projectId","dataStoreId"]),l=h.next(),n;try{for(;!l.done;l=h.next()){var p=l.value;g(e[p])||(e.debug&&c(p+" missing"),k=!1)}}finally{l&&!l.done&&(n=h.return)&&n.call(h)}typeof e.logEvent!=="object"&&(e.debug&&c("logEvent object missing"),k=!1);g(e.locationId)?["global","us","eu"].includes(e.locationId)||(e.debug&&c("invalid locationId "+
e.locationId),k=!1):(e.debug&&c("locationId missing"),k=!1);return k}function q(e,k){var h={global:"discoveryengine.googleapis.com",us:"us-discoveryengine.googleapis.com",eu:"eu-discoveryengine.googleapis.com"};h=h[e.locationId];return"https://"+h+"/v1beta/projects/"+encodeURIComponent(e.projectId||"")+"/locations/"+encodeURIComponent(e.locationId||"")+"/dataStores/"+encodeURIComponent(e.dataStoreId||"")+"/userEvents:collect?key="+encodeURIComponent(e.apiKey||"")+"&uri="+encodeURIComponent(d.substring(0,
1500))+"&user_event="+encodeURIComponent(JSON.stringify(e.logEvent||""))+"&ets="+k}typeof a==="object"&&(a=Object.create(a),a.locationId=a.locationId||"global",m(a)&&(b.width=1,b.height=1,b.src=q(a,f)))},logEvent:function(a){var b=function(){};typeof window==="object"&&typeof window.console==="object"&&typeof window.console.log==="function"&&(b=window.console.log);var c="";typeof window==="object"&&typeof window.location==="object"&&typeof window.location.href==="string"&&(c=window.location.href);
cloud_discoveryengine.collect(a,document.createElement("img"),b,c,Date.now())}};typeof document!=="undefined"&&(typeof _gre!=="undefined"?cloud_discoveryengine.logEvent(_gre):cloud_discoveryengine.logEvent({}));
