(function(){var n,aa,ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ea(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");} 
var fa=ea(this),ha=typeof Symbol==="function"&&typeof Symbol("x")==="symbol",q={},ia={};function t(a,b,c){if(!c||a!=null){c=ia[b];if(c==null)return a[b];c=a[c];return c!==void 0?c:a[b]}} 
function u(a,b,c){if(b)a:{var d=a.split(".");a=d.length===1;var e=d[0],f;!a&&e in q?f=q:f=fa;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ha&&c==="es6"?f[d]:null;b=b(c);b!=null&&(a?ba(q,d,{configurable:!0,writable:!0,value:b}):b!==c&&(ia[d]===void 0&&(a=Math.random()*1E9>>>0,ia[d]=ha?fa.Symbol(d):"$jscp$"+a+"$"+d),ba(f,ia[d],{configurable:!0,writable:!0,value:b})))}}function ja(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}} 
function w(a){var b=typeof q.Symbol!="undefined"&&t(q.Symbol,"iterator")&&a[t(q.Symbol,"iterator")];if(b)return b.call(a);if(typeof a.length=="number")return{next:ja(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ka(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ma(a){return na(a,a)}function na(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)} 
var oa=ha&&typeof t(Object,"assign")=="function"?t(Object,"assign"):function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)E(d,e)&&(a[e]=d[e])}return a};u("Object.assign",function(a){return a||oa},"es6");function pa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}u("globalThis",function(a){return a||fa},"es_2020"); 
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.v=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.v};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b},"es6"); 
u("Symbol.iterator",function(a){if(a)return a;a=(0,q.Symbol)("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(ja(this))}});return a},"es6");function qa(a){a={next:a};a[t(q.Symbol,"iterator")]=function(){return this};return a} 
u("WeakMap",function(a){function b(g){this.v=(f+=Math.random()+1).toString();if(g){g=w(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(g){var h=typeof g;return h==="object"&&g!==null||h==="function"}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),k=new a([[g,2],[h,3]]);if(k.get(g)!=2||k.get(h)!=3)return!1;k.delete(g);k.set(h,4);return!k.has(g)&&k.get(h)==4}catch(l){return!1}}())return a;var e="$jscomp_hidden_"+Math.random(), 
f=0;b.prototype.set=function(g,h){if(!d(g))throw Error("Invalid WeakMap key");if(!E(g,e)){var k=new c;ba(g,e,{value:k})}if(!E(g,e))throw Error("WeakMap key fail: "+g);g[e][this.v]=h;return this};b.prototype.get=function(g){return d(g)&&E(g,e)?g[e][this.v]:void 0};b.prototype.has=function(g){return d(g)&&E(g,e)&&E(g[e],this.v)};b.prototype.delete=function(g){return d(g)&&E(g,e)&&E(g[e],this.v)?delete g[e][this.v]:!1};return b},"es6"); 
u("Map",function(a){function b(){var h={};return h.G=h.next=h.head=h}function c(h,k){var l=h[1];return qa(function(){if(l){for(;l.head!=h[1];)l=l.G;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h[0][l];if(m&&E(h[0],l))for(h=0;h<m.length;h++){var p=m[h];if(k!==k&&p.key!==p.key||k===p.key)return{id:l,list:m,index:h,entry:p}}return{id:l, 
list:m,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=w(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!t(a.prototype,"entries")||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(w([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=t(k,"entries").call(k),m=l.next();if(m.done||m.value[0]!=h||m.value[1]!="s")return!1;m=l.next();return m.done|| 
m.value[0].x!=4||m.value[1]!="t"||!l.next().done?!1:!0}catch(p){return!1}}())return a;var f=new q.WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],G:this[1].G,head:this[1],key:h,value:k},l.list.push(l.entry),this[1].G.next=l.entry,this[1].G=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id], 
h.entry.G.next=h.entry.next,h.entry.next.G=h.entry.G,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].G=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})}; 
e.prototype.forEach=function(h,k){for(var l=t(this,"entries").call(this),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[t(q.Symbol,"iterator")]=t(e.prototype,"entries");var g=0;return e},"es6");function ra(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[t(q.Symbol,"iterator")]=function(){return e};return e} 
u("Array.prototype.entries",function(a){return a?a:function(){return ra(this,function(b,c){return[b,c]})}},"es6");u("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}},"es6");u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)E(b,d)&&c.push([d,b[d]]);return c}},"es8");u("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}},"es6"); 
u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||t(Object,"is").call(Object,f,b))return!0}return!1}},"es7"); 
u("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}},"es6");u("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)E(b,d)&&c.push(b[d]);return c}},"es8"); 
u("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}},"es8");u("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}},"es6");/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var sa=this||self;function ua(a){a=parseFloat(a);return isNaN(a)||a>1||a<0?0:a};function wa(a){wa[" "](a);return a}wa[" "]=function(){};function xa(a){try{var b;if(b=!!a&&a.location.href!=null)a:{try{wa(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}};function ya(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function za(){var a=sa.navigator;return a&&(a=a.userAgent)?a:""};/* 
 
 Copyright Google LLC 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var Aa=q.globalThis.trustedTypes,Ba;function Ca(){var a=null;if(!Aa)return a;try{var b=function(c){return c};a=Aa.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a}function Da(){Ba===void 0&&(Ba=Ca());return Ba};function Ea(a){this.v=a}Ea.prototype.toString=function(){return this.v+""};function Fa(a){var b=Da();a=b?b.createScriptURL(a):a;return new Ea(a)}function Ga(a){if(a instanceof Ea)return a.v;throw Error("");};function Ja(a){this.v=a}Ja.prototype.toString=function(){return this.v+""};function Ka(a,b){a.src=Ga(b);var c;b=a.ownerDocument;b=b===void 0?document:b;var d;b=(d=(c=b).querySelector)==null?void 0:d.call(c,"script[nonce]");(c=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&a.setAttribute("nonce",c)};var La=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var Ma=ya(function(){return za().indexOf("MSIE")!=-1});function Na(a){return za().indexOf(a)!=-1}var Oa=ya(function(){var a=Math.random;return["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"].some(Na)||a()<1E-4});function Pa(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};function Qa(){if(!q.globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);q.globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}};function Ra(a){var b=pa.apply(1,arguments);if(b.length===0)return Fa(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Fa(c)}function Sa(a,b,c,d){function e(g,h){g!=null&&(Array.isArray(g)?g.forEach(function(k){return e(k,h)}):(b+=f+encodeURIComponent(h)+"="+encodeURIComponent(g),f="&"))}var f=b.length?"&":"?";d.constructor===Object&&(d=t(Object,"entries").call(Object,d));Array.isArray(d)?d.forEach(function(g){return e(g[1],g[0])}):d.forEach(e);return Fa(a+b+c)};function Ta(a){return/^true$/.test(a)}function Ua(a,b){if(!a||!b.head)return null;var c=Va("META");b.head.appendChild(c);c.httpEquiv="origin-trial";c.content=a;return c}function Va(a,b){b=b===void 0?document:b;return b.createElement(String(a).toLowerCase())};var Wa=ua("0.20"),Xa=ua("0.002"),Ya=ua("1.0"),$a=ua("1.0"),bb=ua("0.00"),cb=ua("0.00"),db=Ta("true"),eb=Ta("true"),fb=Ta("true"),gb=Ta("true"),hb=Ta("true");var ib=null;function jb(a){a=a===void 0?window:a;if(ib===null){ib="";try{var b="";try{b=a.top.location.hash}catch(d){b=a.location.hash}if(b){var c=b.match(/\bdeid=([\d,]+)/);ib=c?c[1]:""}}catch(d){}}return ib} 
function kb(a,b,c){var d=G;if(c?d.v.hasOwnProperty(c)&&d.v[c]==="":1){var e=e===void 0?sa:e;e=(e=jb(e))?(e=e.match(new RegExp("\\b("+a.join("|")+")\\b")))?e[0]:null:null;if(e)a=e;else a:{if(!Ma()&&!Oa()&&(e=Math.random(),e<b)){e=Qa();a=a[Math.floor(e*a.length)];break a}a=null}a&&a!==""&&(c?d.v.hasOwnProperty(c)&&(d.v[c]=a):d.Z[a]=!0)}}function H(a){var b=G;return b.v.hasOwnProperty(a)?b.v[a]:""} 
function lb(){var a=G,b=[];Pa(a.Z,function(c,d){b.push(d)});Pa(a.v,function(c){c!==""&&b.push(c)});return b};var mb={wa:2,Da:13,Ca:14,za:16,ya:17,xa:18,va:19,Fa:20,Ea:21,ua:22,qa:23},G=null;function nb(){return!!G&&(H(20)=="466465926"||H(20)=="466465925")}function ob(){return!!G&&H(16)=="592230571"}function pb(){return!!G&&(H(22)=="512247839"||H(22)=="512247838")};function qb(a){var b=b===void 0?sa:b;var c,d;return((c=b.performance)==null?void 0:(d=c.timing)==null?void 0:d[a])||0};function rb(){var a=sb,b="S";if(a.S&&a.hasOwnProperty(b))return a.S;b=new a;return a.S=b};var tb={Aa:0,ra:1,Ba:2,ta:3,sa:4};function sb(){this.v={}}function ub(a,b,c){typeof c==="number"&&c>0&&(a.v[b]=Math.round(c))}function vb(a){var b=rb();var c=c===void 0?sa:c;c=c.performance;ub(b,a,c&&c.now?c.now():null)}function wb(){function a(){return ub(b,0,qb("loadEventStart")-qb("navigationStart"))}var b=rb();qb("loadEventStart")!=0?a():window.addEventListener("load",a)}function xb(a,b){b.google_tag_manager&&b.google_tag_manager._li&&(b=b.google_tag_manager._li,ub(a,4,b.cbt),ub(a,3,b.cst))} 
function yb(){var a=rb();return t(Object,"values").call(Object,tb).map(function(b){return[b,a.v[b]||0]})};var zb=Ta("false");function Ab(a){return typeof a==="function"}function Bb(a){return typeof a==="string"}function Cb(a,b){if(a&&Array.isArray(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]}function Db(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])}function I(){return(new Date(Date.now())).getTime()}function Eb(a,b){return a.length>=b.length&&a.substring(a.length-b.length,a.length)===b} 
function Gb(a){for(var b=0;b<3;++b)try{var c=decodeURIComponent(a).replace(/\+/g," ");if(c===a)break;a=c}catch(d){return""}return a};var Hb={};function J(a){var b=Hb.TAGGING;b||(b=Hb.TAGGING=[]);b[a]=!0};var M=window,N=document,Ib=navigator,Jb={async:1,nonce:1,onerror:1,onload:1,src:1,type:1},Kb={height:1,onload:1,src:1,style:1,width:1};function Lb(a,b,c){b&&Db(b,function(d,e){d=d.toLowerCase();c.hasOwnProperty(d)||a.setAttribute(d,e)})}function Mb(a,b,c,d,e){var f=N.createElement("script");Lb(f,d,Jb);f.type="text/javascript";f.async=d&&d.async===!1?!1:!0;a=Fa(a===null?"null":a===void 0?"undefined":a);Ka(f,a);b&&(f.onload=b);c&&(f.onerror=c);e?e.appendChild(f):Nb.la(f)} 
function Pb(a,b,c){var d=!1;d=d===void 0?!0:d;var e=!1;c||(c=N.createElement("iframe"),e=!0);Lb(c,void 0,Kb);d&&(c.height="0",c.width="0",c.style.display="none",c.style.visibility="hidden");a!==void 0&&(c.src=a);e&&(a=N.body&&N.body.lastChild||N.body||N.head,a.parentNode.insertBefore(c,a));b&&(c.onload=b)}function Qb(){var a=Nb.ea,b=a.apply;var c=pa.apply(0,arguments);c=c instanceof Array?c:ka(w(c));b.call(a,Nb,c)} 
var Rb={cache:"no-store",credentials:"include",keepalive:!0,method:"POST",mode:"no-cors",redirect:"follow"};function Sb(a){if(Ab(M.fetch)){var b=t(Object,"assign").call(Object,{},Rb);try{var c=M.fetch(a,b);if(c)return c.then(function(){}).catch(function(){}),!0}catch(d){}}Nb.pa(a,void 0,void 0);return!0} 
function Tb(){var a=M.performance;if(a&&a.getEntriesByType)try{var b=a.getEntriesByType("navigation");if(b&&b.length>0)var c=b[0].type}catch(d){return"e"}if(!c)return"u";switch(c){case "navigate":return"n";case "back_forward":return"h";case "reload":return"r";case "prerender":return"p";default:return"x"}} 
var Nb={ea:function(a,b,c,d){var e=new Image(1,1);Lb(e,d,{});e.onload=function(){e.onload=null;b&&b()};e.onerror=function(){e.onerror=null;c&&c()};e.src=a;return e},la:function(a){var b=N.getElementsByTagName("script")[0]||N.body||N.head;b.parentNode.insertBefore(a,b)},pa:function(a,b,c){try{var d=Ib.sendBeacon&&Ib.sendBeacon(a)}catch(e){J(15)}d?b==null||b():Qb(a,b,c)}};function Ub(){var a={};var b=M.google_tag_data;M.google_tag_data=b===void 0?a:b;a=M.google_tag_data;return a.ics=a.ics||new Vb}function Vb(){this.entries={};this.waitPeriodTimedOut=this.wasSetLate=this.accessedAny=this.accessedDefault=this.usedImplicit=this.usedUpdate=this.usedDefault=this.usedDeclare=this.active=!1;this.v=[]}n=Vb.prototype; 
n.default=function(a,b,c,d,e,f,g){this.usedDefault||this.usedDeclare||!this.accessedDefault&&!this.accessedAny||(this.wasSetLate=!0);this.usedDefault=this.active=!0;J(19);b==null?J(18):Wb(this,a,b==="granted",c,d,e,f,g)};n.waitForUpdate=function(a,b,c){for(var d=0;d<a.length;d++)Wb(this,a[d],void 0,void 0,"","",b,c)}; 
function Wb(a,b,c,d,e,f,g,h){var k=t(a,"entries"),l=k[b]||{},m=l.region;d=d&&Bb(d)?d.toUpperCase():void 0;e=e.toUpperCase();f=f.toUpperCase();if(e===""||d===f||(d===e?m!==f:!d&&!m)){f=!!(g&&g>0&&l.update===void 0);var p={region:d,declare_region:l.declare_region,implicit:l.implicit,default:c!==void 0?c:l.default,declare:l.declare,update:l.update,quiet:f};if(e!==""||l.default!==!1)k[b]=p;f&&M.setTimeout(function(){k[b]===p&&p.quiet&&(J(2),a.waitPeriodTimedOut=!0,a.clearTimeout(b,void 0,h),a.notifyListeners())}, 
g)}}n.clearTimeout=function(a,b,c){var d=[a],e=c.delegatedConsentTypes,f;for(f in e)e.hasOwnProperty(f)&&e[f]===a&&d.push(f);e=t(this,"entries")[a]||{};a=this.getConsentState(a,c);if(e.quiet){e.quiet=!1;var g=w(d);b=g.next();var h;try{for(;!b.done;b=g.next())Xb(this,b.value)}finally{b&&!b.done&&(h=g.return)&&h.call(g)}}else if(b!==void 0&&a!==b){h=w(d);b=h.next();try{for(;!b.done;b=h.next())Xb(this,b.value)}finally{b&&!b.done&&(g=h.return)&&g.call(h)}}}; 
n.update=function(a,b,c){this.usedDefault||this.usedDeclare||this.usedUpdate||!this.accessedAny||(this.wasSetLate=!0);this.usedUpdate=this.active=!0;if(b!=null){var d=this.getConsentState(a,c),e=t(this,"entries");(e[a]=e[a]||{}).update=b==="granted";this.clearTimeout(a,d,c)}}; 
n.declare=function(a,b,c,d,e){this.usedDeclare=this.active=!0;var f=t(this,"entries"),g=f[a]||{},h=g.declare_region;c=c&&Bb(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(d===""||c===e||(c===d?h!==e:!c&&!h))if(b={region:g.region,declare_region:c,declare:b==="granted",implicit:g.implicit,default:g.default,update:g.update,quiet:g.quiet},d!==""||g.declare!==!1)f[a]=b}; 
n.implicit=function(a,b){this.usedImplicit=!0;var c=t(this,"entries");a=c[a]=c[a]||{};a.implicit!==!1&&(a.implicit=b==="granted")}; 
n.getConsentState=function(a,b){var c=t(this,"entries"),d=c[a]||{},e=d.update;if(e!==void 0)return e?1:2;if(b.usedContainerScopedDefaults){e=b.containerScopedDefaults[a];if(e===3)return 1;if(e===2)return 2}else if(e=d.default,e!==void 0)return e?1:2;if(b==null?0:b.delegatedConsentTypes.hasOwnProperty(a)){a=b.delegatedConsentTypes[a];c=c[a]||{};e=c.update;if(e!==void 0)return e?1:2;if(b.usedContainerScopedDefaults){b=b.containerScopedDefaults[a];if(b===3)return 1;if(b===2)return 2}else if(e=c.default, 
e!==void 0)return e?1:2}e=d.declare;if(e!==void 0)return e?1:2;e=d.implicit;return e!==void 0?e?3:4:0};n.addListener=function(a,b){this.v.push({consentTypes:a,ga:b})};function Xb(a,b){for(var c=0;c<a.v.length;++c){var d=a.v[c];Array.isArray(d.consentTypes)&&d.consentTypes.indexOf(b)!==-1&&(d.ca=!0)}}n.notifyListeners=function(a,b){for(var c=0;c<this.v.length;++c){var d=this.v[c];if(d.ca){d.ca=!1;try{d.ga({consentEventId:a,consentPriorityId:b})}catch(e){}}}};var Yb=[],Zb={};function O(a){return Yb[a]===void 0?!1:Yb[a]};var $b={},ac={delegatedConsentTypes:{},corePlatformServices:{},usedCorePlatformServices:!1,selectedAllCorePlatformServices:!1,containerScopedDefaults:($b.ad_storage=1,$b.analytics_storage=1,$b.ad_user_data=1,$b.ad_personalization=1,$b),usedContainerScopedDefaults:!1};function Q(a){var b=Ub();b.accessedAny=!0;return(Bb(a)?[a]:a).every(function(c){switch(b.getConsentState(c,ac)){case 1:case 3:return!0;case 2:case 4:return!1;default:return!0}})} 
function bc(a){var b=Ub();b.accessedAny=!0;return!(t(b,"entries")[a]||{}).quiet}function cc(a,b){Ub().addListener(a,b)}function dc(a,b){if(b.every(bc))a({});else{var c=!1;cc(b,function(d){!c&&b.every(bc)&&(c=!0,a(d))})}} 
function ec(a,b){function c(){return d.filter(function(g){return Q(g)&&!e[g]})}var d=Bb(b)?[b]:b,e={};b=c();if(b.length!==d.length){var f=function(g){g=w(g);var h=g.next(),k;try{for(;!h.done;h=g.next())e[h.value]=!0}finally{h&&!h.done&&(k=g.return)&&k.call(g)}};f(b);cc(d,function(g){function h(m){m.length!==0&&(f(m),g.consentTypes=m,a(g))}var k=c();if(k.length!==0){var l=t(Object,"keys").call(Object,e).length;k.length+l>=d.length?h(k):M.setTimeout(function(){h(c())},500)}})}};var fc=/:[0-9]+$/,hc=/^\d+\.fls\.doubleclick\.net$/;function ic(a,b){var c={};a=w(a.split("&"));var d=a.next(),e;try{for(;!d.done;d=a.next()){var f=w(d.value.split("=")),g=f.next().value,h=ka(f),k=decodeURIComponent(g.replace(/\+/g," "));if(b===void 0||k===b){var l=h.join("=");c[k]||(c[k]=[]);c[k].push(decodeURIComponent(l.replace(/\+/g," ")))}}}finally{d&&!d.done&&(e=a.return)&&e.call(a)}var m;return(m=c[b])==null?void 0:m[0]} 
function jc(a,b,c,d,e){b&&(b=String(b).toLowerCase());if(b==="protocol"||b==="port")a.protocol=kc(a.protocol)||kc(M.location.protocol);b==="port"?a.port=String(Number(a.hostname?a.port:M.location.port)||(a.protocol==="http"?80:a.protocol==="https"?443:"")):b==="host"&&(a.hostname=(a.hostname||M.location.hostname).replace(fc,"").toLowerCase());var f=kc(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":d="";a&&a.href&&(d=a.href.indexOf("#"),d=d<0?a.href:a.href.substring(0, 
d));a=d;break;case "protocol":a=f;break;case "host":a=a.hostname.replace(fc,"").toLowerCase();c&&(d=/^www\d*\./.exec(a))&&d[0]&&(a=a.substring(d[0].length));break;case "port":a=String(Number(a.port)||(f==="http"?80:f==="https"?443:""));break;case "path":a.pathname||a.hostname||J(1);a=a.pathname.charAt(0)==="/"?a.pathname:"/"+a.pathname;a=a.split("/");(d||[]).indexOf(a[a.length-1])>=0&&(a[a.length-1]="");a=a.join("/");break;case "query":a=a.search.replace("?","");e&&(a=ic(a,e));break;case "extension":a= 
a.pathname.split(".");a=a.length>1?a[a.length-1]:"";a=a.split("/")[0];break;case "fragment":a=a.hash.replace("#","");break;default:a=a&&a.href}return a}function kc(a){return a?a.replace(":","").toLowerCase():""}var lc={},mc=0; 
function nc(a){var b=lc[a];if(!b){b=N.createElement("a");a&&(b.href=a);var c=b.pathname;c[0]!=="/"&&(a||J(1),c="/"+c);var d=b.hostname.replace(fc,"");b={href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port};mc<5&&(lc[a]=b,mc++)}return b};function oc(a,b,c,d){var e,f=Number(a.U!=null?a.U:void 0);f!==0&&(e=new Date((b||I())+1E3*(f||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:e,K:d}};var pc=["ad_storage","ad_user_data"];function qc(a,b){if(a)if(b===null||b===void 0||b==="")J(33);else{var c=rc(!1);c.error!==0?J(34):c.value?(c.value[a]=b,sc(c)!==0&&J(36)):J(35)}else J(32)}function tc(a){if(!a)return J(27),{error:10};var b=rc();if(b.error!==0)return J(29),b;if(!b.value)return J(30),{error:2};if(!(a in b.value))return J(31),{value:void 0,error:15};a=b.value[a];return a===null||a===void 0||a===""?(J(28),{value:void 0,error:11}):{value:a,error:0}} 
function uc(a){if(a){var b=rc(!1);b.error!==0?J(38):b.value?a in b.value?(delete b.value[a],sc(b)!==0&&J(41)):J(40):J(39)}else J(37)} 
function rc(a){a=a===void 0?!0:a;if(!Q(pc))return J(43),{error:3};try{if(!M.localStorage)return J(44),{error:1}}catch(f){return J(45),{error:14}}var b={schema:"gcl",version:1},c=void 0;try{c=M.localStorage.getItem("_gcl_ls")}catch(f){return J(46),{error:13}}try{if(c){var d=JSON.parse(c);if(d&&typeof d==="object")b=d;else return J(47),{error:12}}}catch(f){return J(48),{error:8}}if(b.schema!=="gcl")return J(49),{error:4};if(b.version!==1)return J(50),{error:5};try{var e=vc(b);a&&e&&sc({value:b,error:0})}catch(f){return J(48), 
{error:8}}return{value:b,error:0}}function vc(a){if(!a||typeof a!=="object")return!1;if("expires"in a&&"value"in a){var b;typeof a.expires==="number"?b=a.expires:b=typeof a.expires==="string"?Number(a.expires):NaN;if(isNaN(b)||!(Date.now()<=b))return a.value=null,a.error=9,J(54),!0}else{b=!1;var c=w(t(Object,"keys").call(Object,a)),d=c.next(),e;try{for(;!d.done;d=c.next())b=vc(a[d.value])||b}finally{d&&!d.done&&(e=c.return)&&e.call(c)}return b}return!1} 
function sc(a){if(a.error)return a.error;if(!a.value)return J(42),2;a=a.value;try{var b=JSON.stringify(a)}catch(c){return J(52),6}try{M.localStorage.setItem("_gcl_ls",b)}catch(c){return J(53),7}return 0};var wc={M:"value",F:"conversionCount",V:1},xc=[wc,{M:"timeouts",F:"timeouts",V:0},{M:"errors",F:"errors",V:0},{M:"eopCount",F:"endOfPageCount",V:0}];function yc(a){return Q(["ad_storage","ad_user_data"])?!a.oa||O(a.oa):!1}function zc(a){return Q(["ad_storage","ad_user_data"])?!a.ka||O(a.ka):!1};function Ac(){return Q(["ad_storage","ad_user_data"])&&O(7)};function Bc(a,b,c,d){var e;return(e=Cc(function(f){return f===a},b,c,d)[a])!=null?e:[]}function Cc(a,b,c,d){if(Dc(d)){d={};b=String(b||Ec()).split(";");for(var e=0;e<b.length;e++){var f=b[e].split("="),g=f[0].trim();if(g&&a(g)){(f=f.slice(1).join("=").trim())&&c&&(f=decodeURIComponent(f));var h=void 0,k=void 0;((h=d)[k=g]||(h[k]=[])).push(f)}}a=d}else a={};return a} 
function Fc(a,b,c){var d=Gc,e=["ad_storage","ad_user_data"];if(Dc(e)){a=Hc(a,d,e);if(a.length===1)return a[0];if(a.length!==0){a=Ic(a,function(f){return f.fa},b);if(a.length===1)return a[0];a=Ic(a,function(f){return f.na},c);return a[0]}}}function Jc(a,b,c,d){var e=Ec();M.origin!=="null"&&(M.document.cookie=a);a=Ec();return e!==a||c!==void 0&&Bc(b,a,!1,d).indexOf(c)>=0} 
function Kc(a,b,c){function d(p,r,v){if(v==null)return delete g[r],p;g[r]=v;return p+"; "+r+"="+v}function e(p,r){if(r==null)return p;g[r]=!0;return p+"; "+r}if(Dc(c.K)){if(b==null)var f=a+"=deleted; expires="+(new Date(0)).toUTCString();else c.encode&&(b=encodeURIComponent(b)),b=Lc(b),f=a+"="+b;var g={};f=d(f,"path",c.path);if(c.expires instanceof Date)var h=c.expires.toUTCString();else c.expires!=null&&(h=c.expires);f=d(f,"expires",h);f=d(f,"max-age",c.Ha);f=d(f,"samesite",c.Ia);c.secure&&(f=e(f, 
"secure"));if((h=c.domain)&&h.toLowerCase()==="auto"){h=Mc();for(var k=0;k<h.length;++k){var l=h[k]!=="none"?h[k]:void 0,m=d(f,"domain",l);m=e(m,c.flags);if(!Nc(l,c.path)&&Jc(m,a,b,c.K))break}}else h&&h.toLowerCase()!=="none"&&(f=d(f,"domain",h)),f=e(f,c.flags),Nc(h,c.path)||Jc(f,a,b,c.K)}}function Oc(a,b,c){c.path==null&&(c.path="/");c.domain||(c.domain="auto");Kc(a,b,c)} 
function Ic(a,b,c){for(var d=[],e=[],f,g=0;g<a.length;g++){var h=a[g],k=b(h);k===c?d.push(h):f===void 0||k<f?(e=[h],f=k):k===f&&e.push(h)}return d.length>0?d:e}function Hc(a,b,c){var d=[];a=Bc(a,void 0,void 0,c);for(c=0;c<a.length;c++){var e=a[c].split("."),f=e.shift();if(!b||!f||b.indexOf(f)!==-1)if(f=e.shift())f=f.split("-"),d.push({Ga:a[c],da:e.join("."),fa:Number(f[0])||1,na:Number(f[1])||1})}return d}function Lc(a){a&&a.length>1200&&(a=a.substring(0,1200));return a} 
var Pc=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Qc=/(^|\.)doubleclick\.net$/i;function Nc(a,b){return a!==void 0&&(Qc.test(M.document.location.hostname)||b==="/"&&Pc.test(a))}function Rc(a){if(!a)return 1;var b=a;O(4)&&a==="none"&&(b=M.document.location.hostname);b=b.indexOf(".")===0?b.substring(1):b;return b.split(".").length}function Sc(a){if(!a||a==="/")return 1;a[0]!=="/"&&(a="/"+a);a[a.length-1]!=="/"&&(a+="/");return a.split("/").length-1} 
function Tc(a,b){a=""+Rc(a);b=Sc(b);b>1&&(a+="-"+b);return a}function Ec(){return M.origin!=="null"?M.document.cookie:""}function Dc(a){return a&&O(5)?(Array.isArray(a)?a:[a]).every(function(b){return bc(b)&&Q(b)}):!0}function Mc(){var a=[],b=M.document.location.hostname.split(".");if(b.length===4){var c=b[b.length-1];if(Number(c).toString()===c)return["none"]}for(c=b.length-2;c>=0;c--)a.push(b.slice(c).join("."));b=M.document.location.hostname;Qc.test(b)||Pc.test(b)||a.push("none");return a};var Gc=["1"],Uc={},Vc={}; 
function Wc(a,b){(b===void 0?0:b)&&yc(wc)&&uc("gcl_ctr");if(b=zc(wc)){b=[wc];b:{var c=tc("gcl_ctr");if(c.error===0&&c.value&&typeof c.value==="object"){c=c.value;try{var d="value"in c&&typeof c.value==="object"?c.value:void 0;break b}catch(v){}}d=void 0}c={};b=w(b);var e=b.next(),f;try{for(;!e.done;e=b.next()){var g=e.value;if(d&&yc(g)){var h=d[g.M];h===void 0||t(Number,"isNaN").call(Number,h)?c[g.F]=-1:c[g.F]=Number(h)}else c[g.F]=-1}}finally{e&&!e.done&&(f=b.return)&&f.call(b)}b=c[wc.F]===-1}if(b){f= 
{};f=(f[wc.F]=0,f);g=w(xc);h=g.next();var k;try{for(;!h.done;h=g.next()){var l=h.value;l!==wc&&zc(l)&&(f[l.F]=0)}}finally{h&&!h.done&&(k=g.return)&&k.call(g)}k=I();a=oc(a||{},k,!0);l={};g=w(xc);h=g.next();var m;try{for(;!h.done;h=g.next()){var p=h.value,r=f[p.F];r!==void 0&&r!==-1&&(l[p.M]=r)}}finally{h&&!h.done&&(m=g.return)&&m.call(g)}l.creationTimeMs=k;qc("gcl_ctr",{value:l,expires:Number(a.expires)})}} 
function Xc(a,b){(b===void 0?0:b)&&Ac()&&uc("last_convs");if(!(b=!(Q(["ad_storage","ad_user_data"])&&O(8))))a:{if(Ac()){var c=tc("last_convs");if(c.error===0&&c.value&&typeof c.value==="object"&&(c=c.value,c.value&&Array.isArray(c.value))){var d=c.value;if(!(d.length>1)){c=[];d=w(d);var e=d.next(),f;try{for(;!e.done;e=d.next()){var g=e.value;if(typeof g!=="object"||g===null||typeof g.random!=="number"||typeof g.label!=="string"||g.label.length>200){b=void 0;break a}c.push({random:g.random,label:g.label})}}finally{e&& 
!e.done&&(f=d.return)&&f.call(d)}b=c;break a}}}b=void 0}b||(f=[],!Ac()||f.length>1||f.length===1&&f[0].label.length>200||(a=a||{},qc("last_convs",{value:f,expires:Number(oc(a).expires)})))}function Yc(a,b,c,d){b=["1",Tc(c.domain,c.path),b].join(".");c=oc(c,d);c.K=["ad_storage","ad_user_data"];Oc(a,b,c)} 
function Zc(a,b,c){var d;b=(d=Fc(a,Rc(b),Sc(c)))==null?void 0:d.da;if(!b)return!1;c=b.split(".");c.length===3?Vc[a]={sessionId:c[0]+"."+c[1],J:Number(c[2])||0,R:0}:c.length>=2&&(Uc[a]=c[0]+"."+c[1],c.shift(),c.shift(),c.length>=3&&(d={sessionId:c[0]==="-"?void 0:c[0]+"."+c[1],J:Number(c[2])||0,R:0},O(13)&&c.length>=6&&(b=c[3]+"."+c[4],c=Number(c[5])||0,b&&c!==0&&(d.ba=b,d.R=c)),Vc[a]=d));return!0}function $c(a){return(a||"_gcl")+"_au"};function ad(a,b,c){a=bd(a,!0);if(a[b])return!1;a[b]=[];a[b][0]=c;return!0}function bd(a,b){var c=a.GooglebQhCsO;c||(c={},b&&(a.GooglebQhCsO=c));return c};var cd={},dd=null; 
function ed(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);e>255&&(b[c++]=e&255,e>>=8);b[c++]=e}a=4;a===void 0&&(a=0);if(!dd)for(dd={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;e<5;e++){var f=c.concat(d[e].split(""));cd[e]=f;for(var g=0;g<f.length;g++){var h=f[g];dd[h]===void 0&&(dd[h]=g)}}a=cd[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=f=0;f<b.length-2;f+=3){var k=b[f],l=b[f+1];h=b[f+2];g=a[k>>2];k=a[(k& 
3)<<4|l>>4];l=a[(l&15)<<2|h>>6];h=a[h&63];c[e++]=g+k+l+h}g=0;h=d;switch(b.length-f){case 2:g=b[f+1],h=a[(g&15)<<2]||d;case 1:b=b[f],c[e]=a[b>>2]+a[(b&3)<<4|g>>4]+h+d}return c.join("")};var fd=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function gd(a){var b=a.match(fd);a=b[5];var c=b[6];b=b[7];var d="";a&&(d+=a);c&&(d+="?"+c);b&&(d+="#"+b);return d}function hd(a,b,c,d){for(var e=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var f=a.charCodeAt(b-1);if(f==38||f==63)if(f=a.charCodeAt(b+e),!f||f==61||f==38||f==35)return b;b+=e+1}return-1}var id=/#|$/; 
function jd(a,b){var c=a.search(id),d=hd(a,0,b,c);if(d<0)return null;var e=a.indexOf("&",d);if(e<0||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,e!==-1?e:0).replace(/\+/g," "))}var kd=/[?&]($|#)/; 
function ld(a,b,c){for(var d=a.search(id),e=0,f,g=[];(f=hd(a,e,b,d))>=0;)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.slice(e));a=g.join("").replace(kd,"$1");c=c!=null?"="+encodeURIComponent(String(c)):"";(b+=c)?(c=a.indexOf("#"),c<0&&(c=a.length),d=a.indexOf("?"),d<0||d>c?(d=c,e=""):e=a.substring(d+1,c),c=[a.slice(0,d),e,a.slice(c)],a=c[1],c[1]=b?a?a+"&"+b:b:a,b=c[0]+(c[1]?"?"+c[1]:"")+c[2]):b=a;return b};function md(a,b,c,d,e,f){var g=jd(c,"fmt");if(d){var h=jd(c,"random"),k=jd(c,"label")||"";if(!h)return;h=ed(decodeURIComponent(k.replace(/\+/g," "))+":"+decodeURIComponent(h.replace(/\+/g," ")));if(!ad(a,h,d))return}g&&Number(g)!==4?(c=ld(c,"rfmt",g),c=ld(c,"fmt",4)):g||(c=ld(c,"fmt",4));Mb(c,function(){a.google_noFurtherRedirects&&d&&(a.google_noFurtherRedirects=null,d())},function(){e==null||e()},f,b.getElementsByTagName("script")[0].parentElement||void 0);return c};var R={},nd=(R.k={D:/^[\w-]+$/},R.b={D:/^[\w-]+$/,W:!0},R.i={D:/^[1-9]\d*$/},R.h={D:/^\d+$/},R.t={D:/^[1-9]\d*$/},R.d={D:/^[A-Za-z0-9_-]+$/},R.j={D:/^\d+$/},R.u={D:/^[1-9]\d*$/},R.l={D:/^[01]$/},R.o={D:/^[1-9]\d*$/},R.g={D:/^[01]$/},R.s={D:/^.+$/},R.m={D:/^[01]$/},R);var od={},sd=(od[5]={Y:{2:pd},T:"2",N:["k","i","b","u"]},od[4]={Y:{2:pd,GCL:qd},T:"2",N:["k","i","b","m"]},od[2]={Y:{GS2:pd,GS1:rd},T:"GS2",N:"sogtjlhd".split("")},od); 
function pd(a,b){a=a.split(".");if(a.length===3){var c=a[2];if(c.indexOf("$")===-1&&c.indexOf("%24")!==-1)try{c=decodeURIComponent(c)}catch(l){}a={};if(b=sd[b]){b=b.N;c=w(c.split("$"));var d=c.next(),e;try{for(;!d.done;d=c.next()){var f=d.value,g=f[0];if(b.indexOf(g)!==-1)try{var h=decodeURIComponent(f.substring(1)),k=nd[g];k&&(k.W?(a[g]=a[g]||[],a[g].push(h)):a[g]=h)}catch(l){}}}finally{d&&!d.done&&(e=c.return)&&e.call(c)}return a}}} 
function qd(a){a=a.split(".");a.shift();var b=a.shift(),c=a.shift(),d={};return d.k=c,d.i=b,d.b=a,d}function rd(a){a=a.split(".").slice(2);if(!(a.length<5||a.length>7)){var b={};return b.s=a[0],b.o=a[1],b.g=a[2],b.t=a[3],b.j=a[4],b.l=a[5],b.h=a[6],b}};var td=new q.Map([[5,"ad_storage"],[4,["ad_storage","ad_user_data"]],[2,"analytics_storage"]]);function ud(a,b){if(sd[b]){var c=[];a=Bc(a,void 0,void 0,td.get(b));a=w(a);var d=a.next(),e;try{for(;!d.done;d=a.next()){a:{var f=d.value,g=b,h=sd[g];if(h){var k=f.split(".")[0];if(k){var l=h.Y[k];if(l){var m=l(f,g);break a}}}m=void 0}(g=m)&&c.push(vd(g))}}finally{d&&!d.done&&(e=a.return)&&e.call(a)}return c}} 
function wd(a,b,c,d){c=c||{};var e=sd[5];if(e){e=e.T;var f=Tc(c.domain,c.path)||"1";var g=sd[5];if(g){var h=[];g=w(g.N);var k=g.next(),l;try{for(;!k.done;k=g.next()){var m=k.value,p=nd[m];if(p){var r=b[m];if(r!==void 0)if(p.W&&Array.isArray(r)){var v=w(r),x=v.next(),C;try{for(;!x.done;x=v.next())h.push(encodeURIComponent(m+x.value))}finally{x&&!x.done&&(C=v.return)&&C.call(v)}}else h.push(encodeURIComponent(m+r))}}}finally{k&&!k.done&&(l=g.return)&&l.call(g)}b=h.join("$")}else b=void 0;b=[e,f,b].join(".")}else b= 
void 0;b&&(c=oc(c,d,void 0,td.get(5)),Oc(a,b,c))}function xd(a,b){b=b.D;return typeof b==="function"?b(a):b.test(a)}function vd(a){var b=w(t(Object,"keys").call(Object,a)),c=b.next(),d;try{for(var e={};!c.done;e={L:void 0},c=b.next()){var f=c.value,g=a[f];e.L=nd[f];e.L?e.L.W?a[f]=Array.isArray(g)?g.filter(function(h){return function(k){return xd(k,h.L)}}(e)):void 0:typeof g==="string"&&xd(g,e.L)||(a[f]=void 0):a[f]=void 0}}finally{c&&!c.done&&(d=b.return)&&d.call(b)}return a};function S(a){a=a===void 0?0:a;this.value=0;this.value=a}S.prototype.set=function(a){return this.value|=1<<a};function yd(a,b){b<=0||(a.value|=1<<b-1)}S.prototype.get=function(){return this.value};function zd(a){var b=[],c=N.cookie.split(";");a=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$");for(var d=0;d<c.length;d++){var e=c[d].match(a);e&&b.push({X:e[1],value:e[2],timestamp:Number(e[2].split(".")[1])||0})}b.sort(function(f,g){return g.timestamp-f.timestamp});return b} 
function Ad(a,b){a=zd(a);var c={};if(!a||!a.length)return c;for(var d=0;d<a.length;d++){var e=a[d].value.split(".");if(!(e[0]!=="1"||b&&e.length<3||!b&&e.length!==3)&&Number(e[1])){c[a[d].X]||(c[a[d].X]=[]);var f={version:e[0],timestamp:Number(e[1])*1E3,A:e[2]};b&&e.length>3&&(f.labels=e.slice(3));c[a[d].X].push(f)}}return c};var Bd=/^\w+$/,Cd=/^[\w-]+$/,Dd={},Ed=(Dd.aw="FPGCLAW",Dd),T={},Fd=(T.ag="_ag",T.gb="_gb",T.aw="_aw",T.dc="_dc",T.gf="_gf",T.ha="_ha",T.gp="_gp",T.gs="_gs",T);function V(){return["ad_storage","ad_user_data"]}function Y(a){return!O(5)||Q(a)}function Gd(a){function b(){var d=Y(c);d&&a();return d}var c=V();dc(function(){b()||ec(b,c)},c)}function Hd(a){return Id(a).map(function(b){return b.A})} 
function Jd(a,b){function c(e){return function(f){f.aa=e;return f}}b=b===void 0?!1:b;var d=Kd(a.prefix);a=Ld("gb",d);d=Ld("ag",d);if(!d||!a)return[];b=Id(a,b).map(c("gb"));a=Md(d).map(c("ag"));return b.concat(a).sort(function(e,f){return f.timestamp-e.timestamp})}function Nd(a,b,c,d,e){var f=Cb(a,function(g){return g.A===b});f?(f.timestamp<c&&(f.timestamp=c,f.I=e),f.labels=Od(f.labels||[],d||[])):a.push({version:"2",A:b,timestamp:c,labels:d,I:e})} 
function Pd(a){var b=ud(a,5)||[];a=[];b=w(b);var c=b.next(),d;try{for(;!c.done;c=b.next()){var e=c.value,f=e,g=e?(Number(e.i)||0)*1E3:0;g&&Nd(a,f.k,g,f.b||[],e.u)}}finally{c&&!c.done&&(d=b.return)&&d.call(b)}return a.sort(function(h,k){return k.timestamp-h.timestamp})} 
function Id(a,b){b=b===void 0?!1:b;var c=[];Qd(c,a,1);if(b)if(Eb(a,"_aw")){if(a=Rd())a.I=void 0,a.C=a.C||[2],Sd(c,a);Qd(c,"gcl_aw",2)}else Eb(a,"_gb")&&Qd(c,"gcl_gb",2);c.sort(function(d,e){return e.timestamp-d.timestamp});return Td(c)} 
function Ud(a,b){var c=[];a=w(a);var d=a.next(),e;try{for(;!d.done;d=a.next()){var f=d.value;t(c,"includes").call(c,f)||c.push(f)}}finally{d&&!d.done&&(e=a.return)&&e.call(a)}b=w(b);e=b.next();var g;try{for(;!e.done;e=b.next()){var h=e.value;t(c,"includes").call(c,h)||c.push(h)}}finally{e&&!e.done&&(g=b.return)&&g.call(b)}return c} 
function Sd(a,b,c){c=c===void 0?!1:c;var d,e=w(a),f=e.next(),g;try{for(;!f.done;f=e.next()){var h=f.value;if(h.A===b.A){var k=h;break}h.B&&b.B&&h.B.value===b.B.value&&(d=h)}}finally{f&&!f.done&&(g=e.return)&&g.call(e)}if(k){a=k;var l,m;c=(l=k.B)!=null?l:new S;l=(m=b.B)!=null?m:new S;c.value|=l.value;a.B=c;k.timestamp<b.timestamp&&(k.timestamp=b.timestamp,k.I=b.I);k.labels=Ud(k.labels||[],b.labels||[]);k.C=Ud(k.C||[],b.C||[])}else c&&d?t(Object,"assign").call(Object,d,b):a.push(b)} 
function Rd(){var a=tc("gclid");if(!a||a.error||!a.value||typeof a.value!=="object")return null;a=a.value;try{if(!("value"in a&&a.value)||typeof a.value!=="object")return null;var b=a.value,c=b.value;if(!c||!c.match(Cd))return null;var d=b.linkDecorationSource,e=b.linkDecorationSources,f=new S;if(typeof d==="number")if(d){var g=new S;d===1?(yd(g,2),yd(g,3)):yd(g,d);f=g}else f=new S;else typeof e==="number"&&(f.value=e);return{version:"",A:c,timestamp:Number(b.creationTimeMs)||0,labels:[],B:f,C:[2]}}catch(h){return null}} 
function Vd(a){a=tc(a);if(a.error!==0)return null;try{return a.value.reduce(function(b,c){if(!c.value||typeof c.value!=="object")return b;var d=c.value,e=d.value;if(!e||!e.match(Cd))return b;var f=new S,g=d.linkDecorationSources;typeof g==="number"&&(f.value=g);var h;b.push({version:"",A:e,timestamp:Number(d.creationTimeMs)||0,expires:Number(c.expires)||0,labels:(h=d.labels)!=null?h:[],B:f,C:[2]});return b},[])}catch(b){return null}} 
function Qd(a,b,c){if(c===1){var d=Bc(b,N.cookie,void 0,V());d=w(d);var e=d.next(),f;try{for(;!e.done;e=d.next()){var g=Wd(e.value.split(".")),h=g.length===0?null:{version:g[0],A:g[2],timestamp:(Number(g[1])||0)*1E3,labels:g.slice(3)};h!=null&&(h.I=void 0,h.B=new S,h.C=[c],Sd(a,h))}}finally{e&&!e.done&&(f=d.return)&&f.call(d)}}else if(c===2&&(c=Vd(b))){c=w(c);f=c.next();try{for(;!f.done;f=c.next())e=f.value,e.I=void 0,Sd(a,e)}finally{f&&!f.done&&(d=c.return)&&d.call(c)}}} 
function Md(a){return Pd(a).map(function(b){b.B=new S;b.C=[1];return b})}function Od(a,b){if(!a.length)return b;if(!b.length)return a;var c={};return a.concat(b).filter(function(d){return c.hasOwnProperty(d)?!1:c[d]=!0})}function Kd(a){return a&&typeof a==="string"&&a.match(Bd)?a:"_gcl"} 
function Xd(a,b){var c=nc(a);a=jc(c,"query",!1,void 0,"gclid");var d=jc(c,"query",!1,void 0,"gclsrc"),e=jc(c,"query",!1,void 0,"wbraid");if(e){var f=e;try{f=decodeURIComponent(e)}catch(k){}f=f.split(",");e=f.length===2&&f[0]===f[1]?f[0]:e}f=jc(c,"query",!1,void 0,"gbraid");var g=jc(c,"query",!1,void 0,"gad_source"),h=jc(c,"query",!1,void 0,"dclid");!b||a&&d&&e&&f||(b=c.hash.replace("#",""),a=a||ic(b,"gclid"),d=d||ic(b,"gclsrc"),e=e||ic(b,"wbraid"),f=f||ic(b,"gbraid"),g=g||ic(b,"gad_source"));return Yd(a, 
d,h,e,f,g)}function Yd(a,b,c,d,e,f){function g(k,l){h[l]||(h[l]=[]);h[l].push(k)}var h={};h.gclid=a;h.gclsrc=b;h.dclid=c;if(a!==void 0&&a.match(Cd))switch(b){case void 0:g(a,"aw");break;case "aw.ds":g(a,"aw");g(a,"dc");break;case "ds":g(a,"dc");break;case "3p.ds":g(a,"dc");break;case "gf":g(a,"gf");break;case "ha":g(a,"ha")}c&&g(c,"dc");d!==void 0&&Cd.test(d)&&(h.wbraid=d,g(d,"gb"));e!==void 0&&Cd.test(e)&&(h.gbraid=e,g(e,"ag"));f!==void 0&&Cd.test(f)&&(h.gad_source=f,g(f,"gs"));return h} 
function Zd(a,b){function c(){if(Y(d)&&a.length>0){var e=Vd("gcl_gb")||[];a.forEach(function(f){var g=oc(b,f.timestamp,!0);g.expires!==void 0&&Sd(e,{version:"",A:f.A,timestamp:f.timestamp,expires:Number(g.expires),B:f.B,labels:f.labels},!0)});e.length&&qc("gcl_gb",e.map(function(f){var g={value:f.A,creationTimeMs:f.timestamp,linkDecorationSources:f.B?f.B.get():0},h;if((h=f.labels)==null?0:h.length)g.labels=f.labels;return{value:g,expires:Number(f.expires)}}))}}b=b||{};var d=V();dc(function(){Y(d)? 
c():ec(c,d)},d)} 
function $d(a,b,c,d,e){function f(){if(Y(l)){var v=oc(c,h,!0);v.K=l;var x=function(B,Fb){var Za=Ld(B,g);Za&&(Oc(Za,Fb,v),B!=="gb"&&(m=!0))},C=function(B){B=["GCL",k,B];e.length>0&&B.push(e.join("."));return B.join(".")},U=w(["aw","dc","gf","ha","gp"]),W=U.next(),la;try{for(;!W.done;W=U.next()){var ca=W.value;a[ca]&&x(ca,C(a[ca][0]))}}finally{W&&!W.done&&(la=U.return)&&la.call(U)}if((!m||r)&&a.gb){var D=a.gb[0];U=Ld("gb",g);!b&&Id(U).some(function(B){return B.A===D&&B.labels&&B.labels.length>0})|| 
x("gb",C(D))}}if(!p&&a.gbraid&&Y("ad_storage")&&(p=!0,!m||r)){var ta=a.gbraid;x=Ld("ag",g);if(b||!Md(x).some(function(B){return B.A===ta&&B.labels&&B.labels.length>0}))C={},C=(C.k=ta,C.i=""+k,C.b=e,C),wd(x,C,c,h)}ae(a,g,h,c)}c=c||{};e=e||[];var g=Kd(c.prefix),h=d||I(),k=Math.round(h/1E3),l=V(),m=!1,p=!1,r=O(6);dc(function(){f();Y(l)||ec(f,l)},l)} 
function ae(a,b,c,d){if(a.gad_source!==void 0&&Y("ad_storage")){var e=Tb();if(e!=="r"&&e!=="h"&&(b=Ld("gs",b))){e=(e=M.performance)&&Ab(e.now)?e.now():void 0;e=Math.floor((I()-(e||0))/1E3);var f=M.location.hostname;var g=M.location.pathname;f=Gb(f);f.split(".").length>2&&(f=f.replace(/^(www[0-9]*|web|ftp|wap|home|m|w|amp|mobile)\./,""));g=Gb(g);g=g.split(";")[0];g=g.replace(/\/(ar|slp|web|index)?\/?$/,"");g=(f+g).toLowerCase();f=1;var h;if(g)for(f=0,h=g.length-1;h>=0;h--){var k=g.charCodeAt(h);f= 
(f<<6&268435455)+k+(k<<14);k=f&266338304;f=k!==0?f^k>>21:f}g=String(f);f={};a=(f.k=a.gad_source,f.i=""+e,f.u=g,f);wd(b,a,d,c)}}}function Ld(a,b){a=Fd[a];if(a!==void 0)return b+a}function be(a){return Wd(a.split(".")).length!==0?(Number(a.split(".")[1])||0)*1E3:0}function Wd(a){return a.length<3||a[0]!=="GCL"&&a[0]!=="1"||!/^\d+$/.test(a[1])||!Cd.test(a[2])?[]:a}function Td(a){return a.filter(function(b){return Cd.test(b.A)})} 
function ce(){var a=["aw"],b={};if(M.origin!=="null"){for(var c=Kd(b.prefix),d={},e=0;e<a.length;e++)Fd[a[e]]&&(d[a[e]]=Fd[a[e]]);Gd(function(){Db(d,function(f,g){g=Bc(c+g,N.cookie,void 0,V());g.sort(function(m,p){return be(p)-be(m)});if(g.length){var h=g[0];g=be(h);var k=Wd(h.split(".")).length!==0?h.split(".").slice(3):[],l={};h=Wd(h.split(".")).length!==0?h.split(".")[2]:void 0;l[f]=[h];$d(l,!0,b,g,k)}})})}} 
function de(a,b,c,d,e){e=e===void 0?!1:e;var f=[];c=c||{};if(!Y(V()))return f;var g=Id(a,e);var h=[];if(g.length!==0)for(var k={},l=0;l<g.length;l++){var m=g[l],p=m.aa?m.aa:"gcl";if((m.labels||[]).indexOf(b)===-1){f.push(0);var r=!1,v=void 0;if((v=m.C)==null?0:t(v,"includes").call(v,2))r=!0;v=void 0;((v=m.C)==null?0:t(v,"includes").call(v,1))&&!k[p]&&(r=!0,k[p]=!0);r&&h.push(m)}else if(f.push(1),r=void 0,(r=m.C)==null?0:t(r,"includes").call(r,1))k[p]=!0}if(h.length&&!d){d=[];g=!1;h=w(h);k=h.next(); 
var x;try{for(;!k.done;k=h.next()){var C=k.value;l=C;var U=l.version,W=l.A,la=l.timestamp,ca=l.C,D=(l.labels||[]).concat([b]);l=void 0;if(((l=ca)==null?0:t(l,"includes").call(l,1))&&!g){var ta=[U,Math.round(la/1E3),W].concat(D).join("."),B=oc(c,la,!0);B.K=V();Oc(a,ta,B);g=!0}l=void 0;e&&((l=ca)==null?0:t(l,"includes").call(l,2))&&d.push(t(Object,"assign").call(Object,{},C,{labels:D}))}}finally{k&&!k.done&&(x=h.return)&&x.call(h)}d.length&&Zd(d,c)}return f} 
function ee(a,b){b=Kd(b);b=Ld(a,b);if(!b)return 0;a=a==="ag"?Md(b):Id(b);for(var c=b=0;c<a.length;c++)b=Math.max(b,a[c].timestamp);return b}function fe(a){var b=0,c=w(t(Object,"keys").call(Object,a)),d=c.next(),e;try{for(;!d.done;d=c.next())for(var f=a[d.value],g=0;g<f.length;g++)b=Math.max(b,Number(f[g].timestamp))}finally{d&&!d.done&&(e=c.return)&&e.call(c)}return b};var ge=RegExp("^UA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*(?:%3BUA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*)*$"),he=/^~?[\w-]+(?:\.~?[\w-]+)*$/,ie=/^\d+\.fls\.doubleclick\.net$/,je=/;gac=([^;?]+)/,ke=/;gacgb=([^;?]+)/; 
function le(a,b,c){if(ie.test(a.location.host)){if((b=a.location.href.match(c))&&b.length===2&&b[1].match(ge)){a:{try{var d=decodeURIComponent(b[1]);break a}catch(l){}d=void 0}b=d||""}else b="";return b}d=[];a=w(t(Object,"keys").call(Object,b));c=a.next();var e;try{for(;!c.done;c=a.next()){for(var f=c.value,g=[],h=b[f],k=0;k<h.length;k++)g.push(h[k].A);d.push(f+":"+g.join(","))}}finally{c&&!c.done&&(e=a.return)&&e.call(a)}return d.length>0?d.join(";"):""} 
function me(a,b,c,d){var e=Y(V())?Ad("_gac_gb",!0):{},f=[],g=!1,h=w(t(Object,"keys").call(Object,e)),k=h.next(),l;try{for(;!k.done;k=h.next()){var m=k.value,p=de("_gac_gb_"+m,b,c,d);g=g||p.length!==0&&p.some(function(r){return r===1});f.push(m+":"+p.join(","))}}finally{k&&!k.done&&(l=h.return)&&l.call(h)}return{ja:g?f.join(";"):"",ia:le(a,e,ke)}}function ne(a,b){return(a=a.location.href.match(new RegExp(";"+b+"=([^;?]+)")))&&a.length===2&&a[1].match(he)?a[1]:void 0} 
function oe(a,b){a=a.split(".");b=b?b.split("."):[];var c=b.length===a.length?b:void 0;return a.map(function(d,e){d={A:d};if(c&&(e=c[e].split("_"),e.length===2)){d.B=new S(Number(e[0]));e=Number(e[1]);if(e===0)e=[0];else{var f=[];e&1&&f.push(1);e&2&&f.push(2);e&4&&f.push(3);e&8&&f.push(4);e&16&&f.push(5);e=f}d.C=e}return d})} 
function pe(a,b,c,d){var e=e===void 0?!1:e;if(ie.test(a.location.host)){var f=ne(a,d);if(f){if(O(12)){var g=ne(a,d+"_src");return oe(f,g)}if(e){var h=new S;yd(h,2);yd(h,3);return f.split(".").map(function(k){return{A:k,B:h,C:[1]}})}return f.split(".").map(function(k){return{A:k,B:new S,C:[1]}})}}else{if(c==="gclid"){a=Id((b||"_gcl")+"_aw",e);d=Number(Zb[1]===void 0?0:Zb[1]);e=w(qe());b=e.next();try{for(;!b.done;b=e.next())g=b.value,g.timestamp>d&&Sd(a,g)}finally{b&&!b.done&&(f=e.return)&&f.call(e)}return a}if(c=== 
"wbraid")return Id((b||"_gcl")+"_gb",e);if(c==="braids")return Jd({prefix:b},e)}return[]}function qe(){return(ud(Ed.aw,4)||[]).filter(function(a){return a.m==="1"}).map(function(a){return{A:a.k,timestamp:Number(a.i),version:"",C:[5]}})}function re(a,b){return pe(a,b,"gclid","gclaw").map(function(c){return c.A}).join(".")}function se(a,b){return pe(a,b,"wbraid","gclgb").map(function(c){return c.A}).join(".")} 
function te(a,b){var c=se(a,b)!==""||t(Object,"keys").call(Object,Y(V())?Ad("_gac_gb",!0):{}).length>0;a=re(a,b)!==""||le(a,Y(V())?Ad():{},je)!=="";return c&&a}function ue(a){if(Hd("_gcl_aw").length===0&&(!a||Hd(a+"_aw").length===0)){a=Xd(M.location.href,!0);var b=!0,c=w(t(Object,"keys").call(Object,a)),d=c.next(),e;try{for(;!d.done;d=c.next())if(a[d.value]!==void 0){b=!1;break}}finally{d&&!d.done&&(e=c.return)&&e.call(c)}b&&(a=Xd(M.document.referrer,!1),a.gad_source=void 0);$d(a,!1,{});ce()}} 
function ve(a,b,c){a=de((b&&b.prefix||"_gcl")+"_gb",a,b,c,!1);return a.length===0||a.every(function(d){return d===0})?"":a.join(".")};function we(){var a=M.__uspapi;if(Ab(a)){var b="";try{a("getUSPData",1,function(c,d){d&&c&&(c=c.uspString)&&RegExp("^[\\da-zA-Z-]{1,20}$").test(c)&&(b=c)})}catch(c){}return b}};function xe(){var a=a===void 0?document:a;var b;return!((b=a.featurePolicy)==null||!(aa=b.allowedFeatures(),t(aa,"includes")).call(aa,"attribution-reporting"))};var ye="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function ze(a){var b;return(b=a.google_tag_data)!=null?b:a.google_tag_data={}}function Ae(a){a=a.google_tag_data;if(a!=null&&a.uach){a=a.uach;var b=t(Object,"assign").call(Object,{},a);a.fullVersionList&&(b.fullVersionList=a.fullVersionList.slice(0));a=b}else a=null;return a} 
function Be(a){var b,c;return typeof((b=a.navigator)==null?void 0:(c=b.userAgentData)==null?void 0:c.getHighEntropyValues)==="function"}function Ce(){var a=window;if(Be(a)){var b=ze(a);b.uach_promise||(a=a.navigator.userAgentData.getHighEntropyValues(ye).then(function(c){b.uach!=null||(b.uach=c);return c}),b.uach_promise=a)}};var De={id:!0,origin:!0,destination:!0,start_date:!0,end_date:!0,location_id:!0},Ee=/^[a-zA-Z0-9_]+$/,Fe=!1,Ge="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_enable_display_cookie_match google_gtag_event_data google_remarketing_only google_conversion_linker google_tag_for_child_directed_treatment google_tag_for_under_age_of_consent google_allow_ad_personalization_signals google_restricted_data_processing google_conversion_items google_conversion_merchant_id google_user_id google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_gtm_url_processor google_conversion_page_url google_conversion_referrer_url google_gcl_cookie_prefix google_gcl_cookie_path google_gcl_cookie_flags google_gcl_cookie_domain google_gcl_cookie_max_age_seconds google_read_gcl_cookie_opt_out google_basket_feed_country google_basket_feed_language google_basket_discount google_basket_transaction_type google_additional_conversion_params google_additional_params google_transport_url google_gtm_experiments".split(" "); 
function He(a,b){var c=a;return function(){--c;c<=0&&b()}}function Ie(a){return a!=null?encodeURIComponent(String(a)):""}function Je(a){if(a!=null){a=String(a).substring(0,512);var b=a.indexOf("#");return b==-1?a:a.substring(0,b)}return""}function Z(a,b){b=Ie(b);return b!=""&&(a=Ie(a),a!="")?"&".concat(a,"=",b):""}function Ke(a){var b=typeof a;return a==null||b=="object"||b=="function"?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")} 
function Le(a){if(!a||typeof a!="object"||typeof a.join=="function")return"";var b=[],c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];if(d&&typeof d.join==="function"){for(var e,f=[],g=0;g<d.length;++g)e=Ke(d[g]),e!=null&&f.push(e);d=f.length==0?null:f.join(",")}else d=Ke(d);(e=Ke(c))&&d!=null&&b.push(e+"="+d)}return b.join(";")}function Me(a){return typeof a!="number"&&typeof a!="string"?"":Ie(a.toString())} 
function Ne(a,b){if(b.google_read_gcl_cookie_opt_out||b.google_remarketing_only||b.google_conversion_domain&&(!b.google_gcl_cookie_prefix||!/^_ycl/.test(b.google_gcl_cookie_prefix)))return"";var c="",d=Oe(b),e={};b.google_gcl_cookie_domain&&(e.domain=b.google_gcl_cookie_domain);b.google_gcl_cookie_flags&&(e.flags=b.google_gcl_cookie_flags);b.google_gcl_cookie_max_age_seconds!=null&&(e.U=b.google_gcl_cookie_max_age_seconds);b.google_gcl_cookie_path&&(e.path=b.google_gcl_cookie_path);d&&(e.prefix=d); 
if(Pe(b)&&b.O)var f=b.P===void 0;else ie.test(a.location.host)?f=!(ne(a,"gclaw")||ne(a,"gac")):(f=Math.max(ee("aw",d),fe(Y(V())?Ad():{})),f=Math.max(ee("gb",d),fe(Y(V())?Ad("_gac_gb",!0):{}))>f);if(f){if(b.P!==void 0)return b.P;c=se(a,d||void 0);f=b.google_conversion_label;var g=ve(f,e,b.O);c=Z("gclgb",c)+(g?Z("mcov",g):"");if(d)return b.P=c;d=me(a,f,e,b.O);a=d.ia;d=d.ja;c+=(a?Z("gacgb",a):"")+(d?Z("gacmcov",d):"");return b.P=c}if(d)return b=re(a,d),Z("gclaw",b);(b=re(a))&&(c=Z("gclaw",b));b=le(a, 
Y(V())?Ad():{},je);return c+(b?Z("gac",b):"")}function Qe(a){function b(d){try{return decodeURIComponent(d),!0}catch(e){return!1}}a=a?a.title:"";if(a==void 0||a=="")return"";a=encodeURIComponent(a);for(var c=256;!b(a.substr(0,c));)c--;return"&tiba="+a.substr(0,c)} 
function Re(a,b,c,d,e){var f="https://",g=c.google_conversion_type==="landing"?"/extclk":"/";switch(d){default:return"";case 2:case 3:var h="googleads.g.doubleclick.net/";var k="pagead/viewthroughconversion/";break;case 1:h="www.google.com/";k="pagead/1p-conversion/";break;case 6:h="www.google.com/";k="ccm/conversion/";break;case 0:h=c.google_conversion_domain||"www.googleadservices.com/";k="pagead/conversion/";break;case 5:h=c.google_conversion_domain||"www.googleadservices.com/";k="ccm/conversion/"; 
break;case 4:h=(h=c.google_gtm_experiments)&&h.apcm?"www.google.com":h&&h.capiorig?c.google_conversion_id+".privacysandbox.googleadservices.com":"www.google.com/",k="pagead/privacysandbox/conversion/"}db&&c.google_transport_url&&(h=c.google_transport_url);h[h.length-1]!=="/"&&(h+="/");if(h.indexOf("http://")===0||h.indexOf("https://")===0)f="";f=[f,h,k,Ie(c.google_conversion_id),g,"?random=",Ie(c.google_conversion_time)].join("");g=Z("cv",c.google_conversion_js_version);h=Z("fst",c.google_conversion_first_time); 
k=Z("num",c.google_conversion_snippets);var l=Z("fmt",c.google_conversion_format),m=c.google_remarketing_only?Z("userId",c.google_user_id):"";var p=c.google_tag_for_child_directed_treatment;p=p==null||p!==0&&p!==1?"":Z("tfcd",p);var r=c.google_tag_for_under_age_of_consent;r=r==null||r!==0&&r!==1?"":Z("tfua",r);var v=c.google_allow_ad_personalization_signals;v=v===!1?Z("npa",1):v===!0?Z("npa",0):"";var x=c.google_restricted_data_processing;x=fb?x===!0?Z("rdp",1):x===!1?Z("rdp",0):"":"";var C=Z("value", 
c.google_conversion_value),U=Z("currency_code",c.google_conversion_currency),W=Z("label",c.google_conversion_label),la=Z("oid",c.google_conversion_order_id),ca=Z("bg",c.google_conversion_color);a:{var D=c.google_conversion_language;if(D!=null){D=D.toString();if(2==D.length){D=Z("hl",D);break a}if(5==D.length){D=Z("hl",D.substring(0,2))+Z("gl",D.substring(3,5));break a}}D=""}var ta=Z("guid","ON"),B=!c.google_conversion_domain&&"GooglemKTybQhCsO"in sa&&typeof sa.GooglemKTybQhCsO=="function"?Z("resp", 
"GooglemKTybQhCsO"):"",Fb=Z("disvt",c.google_disable_viewthrough),Za=Z("eid",lb().join());var Ha=[];if(a){var Ia=a.screen;Ia&&(Ha.push(Z("u_h",Ia.height)),Ha.push(Z("u_w",Ia.width)))}Ha=Ha.join("");Ia=Se();var ef=Z("ig",/googleadservices\.com/.test("www.googleadservices.com")?1:0),ab=Le(c.google_custom_params);e=Le(e);e=ab.concat(ab.length>0&&e.length>0?";":"",e);e=e==""?"":"&".concat("data=",encodeURIComponent(e));ab=Ne(b,c);if(!G||H(23)!="658953496"&&H(23)!="658953495"||c.google_read_gcl_cookie_opt_out|| 
c.google_conversion_domain||c.google_remarketing_only)var da="";else{da=Oe(c);var y={};c.google_gcl_cookie_domain&&(y.domain=c.google_gcl_cookie_domain);c.google_gcl_cookie_flags&&(y.flags=c.google_gcl_cookie_flags);c.google_gcl_cookie_max_age_seconds!=null&&(y.U=c.google_gcl_cookie_max_age_seconds);c.google_gcl_cookie_path&&(y.path=c.google_gcl_cookie_path);da&&(y.prefix=da);var K=!1;K=K===void 0?!0:K;var z=$c(y.prefix);if(Uc[z])Wc(y),Xc(y);else if(Zc(z,y.path,y.domain)){z=Vc[$c(y.prefix)]||{id:void 0, 
J:void 0};if(K){K=$c(y.prefix);var A=Uc[K];if(A){var X=A.split(".");if(X.length===2&&(X=Number(X[1])||0)){var F=A;O(13)&&z.ba?F=A+"."+(z.sessionId||"-.-")+"."+(z.J?z.J:Math.floor(I()/1E3))+"."+z.ba+"."+(z.R?z.R:Math.floor(I()/1E3)):z.sessionId&&(F=A+"."+z.sessionId+"."+(z.J?z.J:Math.floor(I()/1E3)));Yc(K,F,y,X*1E3)}}}Wc(y);Xc(y)}else{b:{A=nc(M.location.href);if((X=jc(A,"host",!1))&&X.match(hc)&&(A=jc(A,"path"))&&(A=A.split("auiddc="),A.length>1)){A=A[1].split(";")[0].split("?")[0];break b}A=void 0}A? 
(J(17),Uc[z]=A):K&&(Yc($c(y.prefix),[String(Math.round(Math.random()*2147483647)),Math.round(I()/1E3)].join("."),y),Zc(z,y.path,y.domain),Wc(y,!0),Xc(y,!0))}da=(da=Uc[$c(da)])?Z("auid",da):""}A=c.google_conversion_page_url;y=c.google_conversion_referrer_url;K="";if(b){z=a.top==a?0:(z=a.location.ancestorOrigins)?z[z.length-1]==a.location.origin?1:2:xa(a.top)?1:2;A=A?A:z==1?a.top.location.href:a.location.href;X="";G&&kb(["509562772","509562773"],$a,21);if(G&&(H(21)=="509562773"||H(21)=="509562772")){for(var L, 
va=F=a;F&&F!==F.parent;)F=F.parent,xa(F)&&(va=F);L=va;F=L.location.href;if(L===L.top)var P={url:F,ma:!0};else{va=!1;var Ob=L.document;Ob&&Ob.referrer&&(F=Ob.referrer,L.parent===L.top&&(va=!0));(L=L.location.ancestorOrigins)&&(L=L[L.length-1])&&((P=F)==null?void 0:P.indexOf(L))===-1&&(va=!1,F=L);P={url:F,ma:va}}P.url&&A!==P.url&&(X=P.url)}K+=Z("frm",z);K+=Z("url",Je(A));K+=Z("ref",Je(y||b.referrer));K+=Z("top",Je(X))}a=[g,h,k,l,m,p,r,v,x,C,U,W,la,ca,D,ta,B,Fb,Za,Ha,Ia,ef,e,ab,da,K,Qe(b),Te(c.google_additional_params), 
Te(c.google_remarketing_only?{}:c.google_additional_conversion_params),"&hn="+Ie("www.googleadservices.com"),Ue(a),Ve(a)].join("");b=jb();a+=b.length>0?"&debug_experiment_id="+b:"";if(!c.google_remarketing_only&&!c.google_conversion_domain){b=[Z("mid",c.google_conversion_merchant_id),Z("fcntr",c.google_basket_feed_country),Z("flng",c.google_basket_feed_language),Z("dscnt",c.google_basket_discount),Z("bttype",c.google_basket_transaction_type)].join("");if(c)if(P=c.google_conversion_items){g=[];h=0;for(k=P.length;h< 
k;h++)l=P[h],m=[],l&&(m.push(Me(l.value)),m.push(Me(l.quantity)),m.push(Me(l.item_id)),m.push(Me(l.start_date)),m.push(Me(l.end_date)),g.push("("+m.join("*")+")"));P=g.length>0?"&item="+g.join(""):""}else P="";else P="";b=[a,b,P].join("");a=b.length>4E3?[a,Z("item","elngth")].join(""):b}f+=a;d===1||d===6?f+=[Z("gcp",1),Z("sscte",1),Z("ct_cookie_present",1)].join(""):d==3&&(f+=Z("gcp",1),f+=Z("ct_cookie_present",1));eb&&(d=we(),d!==void 0&&(f+=Z("us_privacy",d||"error")));Pe(c)&&(f=c.O?f+Z("gbcov", 
1):f+Z("gbcov",0));return f}function We(a){if(!zb){var b=document;var c="IFRAME";b.contentType==="application/xhtml+xml"&&(c=c.toLowerCase());c=b.createElement(c);c.style.display="none";c.src="https://bid.g.doubleclick.net/xbbe/pixel?d=KAE";a.body.appendChild(c)}}function Xe(){return new Image} 
function Ye(a,b,c,d,e,f){var g=c.onload_callback;e=e&&g&&g.call?g:function(){};G&&kb(["512247838","512247839"],hb?1:0,22);d+=Z("async","1");g=c.google_gtm_url_processor;Ab(g)&&(d=g(d));var h=(g=c.opt_image_generator)&&g.call,k=pb()?{attributionsrc:""}:void 0;if(!(f=h||!f)){if(c.google_conversion_domain)var l=!1;else try{l=!!md(a,b,d,e,void 0,k)}catch(m){l=!1}f=!l}f&&(a=Xe,h&&(a=g),a=a(),a.src=d,pb()&&a.setAttribute("attributionsrc",""),a.onload=e)} 
function Ze(a,b){G&&H(2)=="376635471"&&(b.readyState==="complete"?We(b):a.addEventListener?a.addEventListener("load",function(){We(b)}):a.attachEvent("onload",function(){We(b)}))} 
function $e(a){if(a.google_conversion_type==="landing"||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets=typeof a.google_conversion_snippets==="number"&&a.google_conversion_snippets>0?a.google_conversion_snippets+1:1;a.google_conversion_first_time===void 0&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version= 
"9";a.google_conversion_format!=0&&a.google_conversion_format!=1&&a.google_conversion_format!=2&&a.google_conversion_format!=3&&(a.google_conversion_format=3);a.google_enable_display_cookie_match!==!1&&(a.google_enable_display_cookie_match=!0);return!0} 
function af(a,b){function c(f){var g=b&&b[f]!=null?b[f]:a[f];if(g!=null&&(f==="google_conversion_domain"||f==="google_transport_url"))if(g==null)g="";else{g=String(g);if(!(g instanceof Ja)){g=String(g).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");var h=Da();g=h?h.createHTML(g):g;g=new Ja(g)}if(g instanceof Ja)g=g.v;else throw Error("");g=g.toString()}d[f]=g}for(var d={},e=0;e<Ge.length;e++)c(Ge[e]);c("onload_callback");return d} 
function bf(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=void 0;d.hasOwnProperty("google_business_vertical")?(e=d.google_business_vertical,b[e]=b[e]||{google_business_vertical:e}):(e="",Object.prototype.hasOwnProperty.call(b,e)||(b[e]={}));e=b[e];for(var f=t(Object,"keys").call(Object,d).filter(function(k){return De.hasOwnProperty(k)}),g=0;g<f.length;g++){var h=f[g];h in e||(e[h]=[]);e[h].push(d[h])}}return t(Object,"values").call(Object,b)} 
function Se(){var a="";ob()&&(a=yb().map(function(b){return b.join("-")}).join("_"));return Z("li",a)}function Ue(a){if(!gb||!a.__gsaExp||!a.__gsaExp.id)return"";a=a.__gsaExp.id;if(!Ab(a))return"";try{var b=Number(a());return isNaN(b)?"":Z("gsaexp",b)}catch(c){return""}} 
function Ve(a){function b(d,e){e!=null&&c.push(d+"="+encodeURIComponent(e))}if(!nb())return"";a=Ae(a);if(!a)return"";var c=[];b("&uaa",a.architecture);b("&uab",a.bitness);b("&uam",a.model);b("&uap",a.platform);b("&uapv",a.platformVersion);a.wow64!=null&&b("&uaw",a.wow64?"1":"0");a.fullVersionList&&b("&uafvl",a.fullVersionList.map(function(d){return encodeURIComponent(d.brand||"")+";"+encodeURIComponent(d.version||"")}).join("|"));return c.join("")} 
function Te(a){if(!a)return"";var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=Z(c,a[c]));return b}function Pe(a){return(a=a.google_gtm_experiments)&&a.gbcov?!0:!1}function Oe(a){return a.google_gcl_cookie_prefix&&a.google_gcl_cookie_prefix!=="_gcl"&&Ee.test(a.google_gcl_cookie_prefix)?a.google_gcl_cookie_prefix:""} 
function cf(a,b){if(!b.google_remarketing_only&&df(a,b)){a=b.google_additional_conversion_params||{};var c=b.google_gtm_experiments;a.capi=c&&c.apcm?"2":"1";b.google_additional_conversion_params=a}} 
function df(a,b){if(b.google_transport_url)return!1;if((b=b.google_gtm_experiments)&&b.apcm)return!0;if(!b||!b.capi)return!1;a:{if(!Fe){Ua("AzMBwcG8UIaKM1GV43UaxMDFsS7hsiLx0FXw9ULTOHJRGxkUVw+UPCxlzz5CudOm+WnidygXLcAHmad6rC6C9QEAAACUeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZWFkc2VydmljZXMuY29tOjQ0MyIsImZlYXR1cmUiOiJBdHRyaWJ1dGlvblJlcG9ydGluZ0Nyb3NzQXBwV2ViIiwiZXhwaXJ5IjoxNzE0NTIxNTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ\x3d\x3d",a);if(!xe()&&!Ua(ff()?"":"A2kc5o2ErHAbqJvF2MHSdYtnc2Bp3n6Jn2kNeko6SgHH6zXBHn0+4BbAW2No9ylVJMkzJAPwMqCVHqXm+IF1DgQAAACKeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZWFkc2VydmljZXMuY29tOjQ0MyIsImZlYXR1cmUiOiJQcml2YWN5U2FuZGJveEFkc0FQSXMiLCJleHBpcnkiOjE2OTUxNjc5OTksImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9",a)){a=!1;break a}Fe=!0}a=xe()}return a}function ff(){return/google\.com$/.test("www.googleadservices.com")};var gf=ma(["https://www.googletagmanager.com/debug/bootstrap"]),hf=!1,jf=document.currentScript&&document.currentScript.src||""; 
function kf(a,b,c){try{if(!hf&&(hf=!0,!c.google_gtm)){var d=void 0,e=void 0,f=jd(a.location.href,"gtm_debug");lf(f)&&(d=2);d||b.referrer.indexOf("https://tagassistant.google.com/")!==0||(d=3);!d&&La(b.cookie.split("; "),"__TAG_ASSISTANT=x")>=0&&(d=4);d||(e=b.documentElement.getAttribute("data-tag-assistant-present"),lf(e)&&(d=5));if(d){var g="AW-"+(c.google_conversion_id||"");if(!a["google.tagmanager.debugui2.queue"]){a["google.tagmanager.debugui2.queue"]=[];var h=Ra(gf),k=new q.Map([["id",g],["src", 
"LEGACY"],["cond",d]]),l=Ga(h).toString(),m=l.split(/[?#]/),p=/[?]/.test(l)?"?"+m[1]:"";var r=Sa(m[0],p,/[#]/.test(l)?"#"+(p?m[2]:m[1]):"",k);var v=Va("SCRIPT",b);Ka(v,r);var x=b.getElementsByTagName("script")[0];x&&x.parentNode&&x.parentNode.insertBefore(v,x)}a["google.tagmanager.debugui2.queue"].push({messageType:"LEGACY_CONTAINER_STARTING",data:{id:g,scriptSource:jf}})}}}catch(C){}}function lf(a){if(a==null||a.length===0)return!1;a=Number(a);var b=Date.now();return a<b+3E5&&a>b-9E5};function mf(a,b){a.onload_callback=a.onload_callback&&typeof a.onload_callback.call=="function"?He(b,a.onload_callback):function(){}} 
function nf(a,b,c){kf(a,b,c);ob()&&(vb(2),c.google_gtm&&xb(rb(),a));var d=!1;if(c.google_conversion_format!=3)return!1;try{if($e(c)){c.google_remarketing_only&&c.google_enable_display_cookie_match&&!zb&&G&&kb(["376635470","376635471"],Wa,2);c.google_remarketing_only&&!c.google_conversion_domain&&G&&kb(["759238990","759238991"],cb,13);!c.google_remarketing_only||c.google_conversion_domain||G&&(H(14)=="759248991"||H(14)=="759248990")||G&&kb(["759248990","759248991"],bb,14);c.google_conversion_linker!== 
!1&&(c.google_gtm||ue(c.google_gcl_cookie_prefix));if(c.google_remarketing_only==1&&c.google_gtag_event_data!=null&&c.google_gtag_event_data.items!=null&&c.google_gtag_event_data.items.constructor===Array&&c.google_gtag_event_data.items.length>0)of(a,b,c);else{var e=c.google_gtm_experiments&&c.google_gtm_experiments.ccmpp;if(c.google_conversion_domain||c.google_transport_url&&c.google_transport_url!=="https://pagead2.googlesyndication.com/")e=!1;var f=!1;ff()&&(f=!0);var g=c.google_additional_params; 
g&&g.dg&&(f=g.dg==="e");g=function(h,k,l){k=k===void 0?!0:k;l=l===void 0?!0:l;Ye(a,b,c,Re(a,b,c,h),k,l)};c.google_gtm_experiments&&c.google_gtm_experiments.fledge&&(c.google_additional_params=c.google_additional_params||{},c.google_additional_params.fledge="1");c.google_remarketing_only?g(2):f?(mf(c,e?3:2),cf(b,c),g(1),g(3),e&&g(6,!0,!1)):(mf(c,e?2:1),cf(b,c),g(0),e&&g(5,!0,!1),Pe(c)&&te(b,Oe(c))&&(c.O=!0,g(0,!1)))}c.google_remarketing_only&&c.google_enable_display_cookie_match&&Ze(a,b);d=!0}}catch(h){}return d} 
function of(a,b,c){var d=bf(c.google_gtag_event_data.items);mf(c,d.length);for(var e=0;e<d.length;e++){var f=d[e];c.google_gtm_experiments&&c.google_gtm_experiments.fledge&&(c.google_additional_params=c.google_additional_params||{},c.google_additional_params.fledge="1");Ye(a,b,c,Re(a,b,c,2,f),!0,!0);c.google_conversion_time=c.google_conversion_time+1}};G=new function(){var a=[];var b=0,c;for(c in mb)a[b++]=mb[c];a=a===void 0?[]:a;this.Z={};this.v={};for(b=0;b<a.length;++b)this.v[a[b]]=""};kb(["466465925","466465926"],Ya,20);nb()&&Ce();G&&kb(["592230570","592230571"],Xa,16);ob()&&(vb(1),wb()); 
function pf(a,b,c,d){function e(m,p,r){r=r===void 0?function(){}:r;var v=new Image;v.onload=m;v.onerror=r;v.src=p}function f(){--g;if(g<=0){var m=bd(a,!1),p=m[b];p&&(delete m[b],m=p[0],typeof m==="function"&&m())}}d=d===void 0?[]:d;var g=c.length+1;if(c.length===2){var h=c[0],k=c[1];hd(h,0,"rmt_tld",h.search(id))>=0&&hd(h,0,"ipr",h.search(id))>=0&&!k.match(fd)[6]&&(k+=gd(h),c[1]=ld(k,"rmt_tld","1"))}for(h={H:0};h.H<c.length;h={H:h.H},h.H++){k=c[h.H];var l=jd(k,"fmt");switch(Number(l)){case 1:case 2:(l= 
a.document.getElementById("goog_conv_iframe"))&&!l.src?Pb(k,f,l):e(f,k);break;case 4:md(a,a.document,k,f);break;case 5:if(a.navigator&&a.navigator.sendBeacon)if(a.navigator.sendBeacon(k,"")){f();break}else k=ld(k,"sendb",2);k=ld(k,"fmt",3);e(f,k);break;default:l=void 0,d&&d[h.H]&&(l=function(m){return function(){Sb(d[m.H])&&f()}}(h)),e(f,k,l)}}f()} 
for(var qf=["GooglemKTybQhCsO"],rf=sa,sf;qf.length&&(sf=qf.shift());)qf.length||pf===void 0?rf[sf]&&rf[sf]!==Object.prototype[sf]?rf=rf[sf]:rf=rf[sf]={}:rf[sf]=pf;window.google_trackConversion=function(a){var b=window,c=document;a=af(b,a);a.google_conversion_format=3;return nf(b,c,a)};}).call(this);
