# 20+ 主流英美新闻网站
SITES = [
    {"name": "New York Times", "domain": "www.nytimes.com", "url": "https://www.nytimes.com/"},
    {"name": "BBC News", "domain": "www.bbc.com", "url": "https://www.bbc.com/news"},
    {"name": "CNN", "domain": "www.cnn.com", "url": "https://www.cnn.com/"},
    {"name": "The Guardian", "domain": "www.theguardian.com", "url": "https://www.theguardian.com/international"},
    {"name": "Wall Street Journal", "domain": "www.wsj.com", "url": "https://www.wsj.com/"},
    {"name": "Washington Post", "domain": "www.washingtonpost.com", "url": "https://www.washingtonpost.com/"},
    {"name": "Reuters", "domain": "www.reuters.com", "url": "https://www.reuters.com/"},
    {"name": "Associated Press", "domain": "apnews.com", "url": "https://apnews.com/"},
    {"name": "NBC News", "domain": "www.nbcnews.com", "url": "https://www.nbcnews.com/"},
    {"name": "ABC News", "domain": "abcnews.go.com", "url": "https://abcnews.go.com/"},
    {"name": "CBS News", "domain": "www.cbsnews.com", "url": "https://www.cbsnews.com/"},
    {"name": "Fox News", "domain": "www.foxnews.com", "url": "https://www.foxnews.com/"},
    {"name": "USA Today", "domain": "www.usatoday.com", "url": "https://www.usatoday.com/"},
    {"name": "Los Angeles Times", "domain": "www.latimes.com", "url": "https://www.latimes.com/"},
    {"name": "Chicago Tribune", "domain": "www.chicagotribune.com", "url": "https://www.chicagotribune.com/"},
    {"name": "Financial Times", "domain": "www.ft.com", "url": "https://www.ft.com/"},
    {"name": "The Economist", "domain": "www.economist.com", "url": "https://www.economist.com/"},
    {"name": "Bloomberg", "domain": "www.bloomberg.com", "url": "https://www.bloomberg.com/"},
    {"name": "CNBC", "domain": "www.cnbc.com", "url": "https://www.cnbc.com/"},
    {"name": "Business Insider", "domain": "www.businessinsider.com", "url": "https://www.businessinsider.com/"},
    {"name": "The Telegraph", "domain": "www.telegraph.co.uk", "url": "https://www.telegraph.co.uk/"},
    {"name": "The Times", "domain": "www.thetimes.com", "url": "https://www.thetimes.com/"},
]
